// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BceCharge.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBceCharge {
  private XinqiBceCharge() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BceChargeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 chargeid = 1;
    boolean hasChargeid();
    int getChargeid();
    
    // optional string invoiceid = 2;
    boolean hasInvoiceid();
    String getInvoiceid();
    
    // optional bool freecharge = 3 [default = false];
    boolean hasFreecharge();
    boolean getFreecharge();
    
    // optional int32 chargemoney = 4;
    boolean hasChargemoney();
    int getChargemoney();
    
    // optional string token = 5;
    boolean hasToken();
    String getToken();
  }
  public static final class BceCharge extends
      com.google.protobuf.GeneratedMessage
      implements BceChargeOrBuilder {
    // Use BceCharge.newBuilder() to construct.
    private BceCharge(Builder builder) {
      super(builder);
    }
    private BceCharge(boolean noInit) {}
    
    private static final BceCharge defaultInstance;
    public static BceCharge getDefaultInstance() {
      return defaultInstance;
    }
    
    public BceCharge getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 chargeid = 1;
    public static final int CHARGEID_FIELD_NUMBER = 1;
    private int chargeid_;
    public boolean hasChargeid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getChargeid() {
      return chargeid_;
    }
    
    // optional string invoiceid = 2;
    public static final int INVOICEID_FIELD_NUMBER = 2;
    private java.lang.Object invoiceid_;
    public boolean hasInvoiceid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getInvoiceid() {
      java.lang.Object ref = invoiceid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          invoiceid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInvoiceidBytes() {
      java.lang.Object ref = invoiceid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        invoiceid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool freecharge = 3 [default = false];
    public static final int FREECHARGE_FIELD_NUMBER = 3;
    private boolean freecharge_;
    public boolean hasFreecharge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getFreecharge() {
      return freecharge_;
    }
    
    // optional int32 chargemoney = 4;
    public static final int CHARGEMONEY_FIELD_NUMBER = 4;
    private int chargemoney_;
    public boolean hasChargemoney() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getChargemoney() {
      return chargemoney_;
    }
    
    // optional string token = 5;
    public static final int TOKEN_FIELD_NUMBER = 5;
    private java.lang.Object token_;
    public boolean hasToken() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          token_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      chargeid_ = 0;
      invoiceid_ = "";
      freecharge_ = false;
      chargemoney_ = 0;
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasChargeid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, chargeid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInvoiceidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, freecharge_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, chargemoney_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chargeid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInvoiceidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, freecharge_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chargemoney_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceChargeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        chargeid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        invoiceid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        freecharge_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        chargemoney_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge build() {
        com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge result = new com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chargeid_ = chargeid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.invoiceid_ = invoiceid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.freecharge_ = freecharge_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chargemoney_ = chargemoney_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.getDefaultInstance()) return this;
        if (other.hasChargeid()) {
          setChargeid(other.getChargeid());
        }
        if (other.hasInvoiceid()) {
          setInvoiceid(other.getInvoiceid());
        }
        if (other.hasFreecharge()) {
          setFreecharge(other.getFreecharge());
        }
        if (other.hasChargemoney()) {
          setChargemoney(other.getChargemoney());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasChargeid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              chargeid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              invoiceid_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              freecharge_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              chargemoney_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              token_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 chargeid = 1;
      private int chargeid_ ;
      public boolean hasChargeid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getChargeid() {
        return chargeid_;
      }
      public Builder setChargeid(int value) {
        bitField0_ |= 0x00000001;
        chargeid_ = value;
        onChanged();
        return this;
      }
      public Builder clearChargeid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chargeid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string invoiceid = 2;
      private java.lang.Object invoiceid_ = "";
      public boolean hasInvoiceid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getInvoiceid() {
        java.lang.Object ref = invoiceid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          invoiceid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInvoiceid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        invoiceid_ = value;
        onChanged();
        return this;
      }
      public Builder clearInvoiceid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        invoiceid_ = getDefaultInstance().getInvoiceid();
        onChanged();
        return this;
      }
      void setInvoiceid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        invoiceid_ = value;
        onChanged();
      }
      
      // optional bool freecharge = 3 [default = false];
      private boolean freecharge_ ;
      public boolean hasFreecharge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getFreecharge() {
        return freecharge_;
      }
      public Builder setFreecharge(boolean value) {
        bitField0_ |= 0x00000004;
        freecharge_ = value;
        onChanged();
        return this;
      }
      public Builder clearFreecharge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        freecharge_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 chargemoney = 4;
      private int chargemoney_ ;
      public boolean hasChargemoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getChargemoney() {
        return chargemoney_;
      }
      public Builder setChargemoney(int value) {
        bitField0_ |= 0x00000008;
        chargemoney_ = value;
        onChanged();
        return this;
      }
      public Builder clearChargemoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chargemoney_ = 0;
        onChanged();
        return this;
      }
      
      // optional string token = 5;
      private java.lang.Object token_ = "";
      public boolean hasToken() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        token_ = value;
        onChanged();
        return this;
      }
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000010);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      void setToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        token_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BceCharge)
    }
    
    static {
      defaultInstance = new BceCharge(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BceCharge)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BceCharge.proto\022 com.xinqihd.sns.games" +
      "erver.proto\"o\n\tBceCharge\022\020\n\010chargeid\030\001 \002" +
      "(\005\022\021\n\tinvoiceid\030\002 \001(\t\022\031\n\nfreecharge\030\003 \001(" +
      "\010:\005false\022\023\n\013chargemoney\030\004 \001(\005\022\r\n\005token\030\005" +
      " \001(\tB\020B\016XinqiBceCharge"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BceCharge_descriptor,
              new java.lang.String[] { "Chargeid", "Invoiceid", "Freecharge", "Chargemoney", "Token", },
              com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.class,
              com.xinqihd.sns.gameserver.proto.XinqiBceCharge.BceCharge.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
