// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BceUserConfig.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBceUserConfig {
  private XinqiBceUserConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BceUserConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bool hideHat = 1;
    boolean hasHideHat();
    boolean getHideHat();
    
    // optional bool hideGlass = 2;
    boolean hasHideGlass();
    boolean getHideGlass();
    
    // optional bool hideSuit = 3;
    boolean hasHideSuit();
    boolean getHideSuit();
    
    // optional bool leadFinished = 4;
    boolean hasLeadFinished();
    boolean getLeadFinished();
    
    // optional bool musicSwitch = 5;
    boolean hasMusicSwitch();
    boolean getMusicSwitch();
    
    // optional bool effectSwitch = 6;
    boolean hasEffectSwitch();
    boolean getEffectSwitch();
    
    // optional int32 musicVolume = 7;
    boolean hasMusicVolume();
    int getMusicVolume();
    
    // optional int32 effectVolume = 8;
    boolean hasEffectVolume();
    int getEffectVolume();
  }
  public static final class BceUserConfig extends
      com.google.protobuf.GeneratedMessage
      implements BceUserConfigOrBuilder {
    // Use BceUserConfig.newBuilder() to construct.
    private BceUserConfig(Builder builder) {
      super(builder);
    }
    private BceUserConfig(boolean noInit) {}
    
    private static final BceUserConfig defaultInstance;
    public static BceUserConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public BceUserConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bool hideHat = 1;
    public static final int HIDEHAT_FIELD_NUMBER = 1;
    private boolean hideHat_;
    public boolean hasHideHat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getHideHat() {
      return hideHat_;
    }
    
    // optional bool hideGlass = 2;
    public static final int HIDEGLASS_FIELD_NUMBER = 2;
    private boolean hideGlass_;
    public boolean hasHideGlass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getHideGlass() {
      return hideGlass_;
    }
    
    // optional bool hideSuit = 3;
    public static final int HIDESUIT_FIELD_NUMBER = 3;
    private boolean hideSuit_;
    public boolean hasHideSuit() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getHideSuit() {
      return hideSuit_;
    }
    
    // optional bool leadFinished = 4;
    public static final int LEADFINISHED_FIELD_NUMBER = 4;
    private boolean leadFinished_;
    public boolean hasLeadFinished() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getLeadFinished() {
      return leadFinished_;
    }
    
    // optional bool musicSwitch = 5;
    public static final int MUSICSWITCH_FIELD_NUMBER = 5;
    private boolean musicSwitch_;
    public boolean hasMusicSwitch() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getMusicSwitch() {
      return musicSwitch_;
    }
    
    // optional bool effectSwitch = 6;
    public static final int EFFECTSWITCH_FIELD_NUMBER = 6;
    private boolean effectSwitch_;
    public boolean hasEffectSwitch() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getEffectSwitch() {
      return effectSwitch_;
    }
    
    // optional int32 musicVolume = 7;
    public static final int MUSICVOLUME_FIELD_NUMBER = 7;
    private int musicVolume_;
    public boolean hasMusicVolume() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getMusicVolume() {
      return musicVolume_;
    }
    
    // optional int32 effectVolume = 8;
    public static final int EFFECTVOLUME_FIELD_NUMBER = 8;
    private int effectVolume_;
    public boolean hasEffectVolume() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getEffectVolume() {
      return effectVolume_;
    }
    
    private void initFields() {
      hideHat_ = false;
      hideGlass_ = false;
      hideSuit_ = false;
      leadFinished_ = false;
      musicSwitch_ = false;
      effectSwitch_ = false;
      musicVolume_ = 0;
      effectVolume_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hideHat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, hideGlass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, hideSuit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, leadFinished_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, musicSwitch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, effectSwitch_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, musicVolume_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, effectVolume_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hideHat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hideGlass_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, hideSuit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, leadFinished_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, musicSwitch_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, effectSwitch_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, musicVolume_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, effectVolume_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        hideHat_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        hideGlass_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        hideSuit_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        leadFinished_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        musicSwitch_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        effectSwitch_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        musicVolume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        effectVolume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig build() {
        com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig result = new com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hideHat_ = hideHat_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hideGlass_ = hideGlass_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hideSuit_ = hideSuit_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.leadFinished_ = leadFinished_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.musicSwitch_ = musicSwitch_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.effectSwitch_ = effectSwitch_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.musicVolume_ = musicVolume_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.effectVolume_ = effectVolume_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.getDefaultInstance()) return this;
        if (other.hasHideHat()) {
          setHideHat(other.getHideHat());
        }
        if (other.hasHideGlass()) {
          setHideGlass(other.getHideGlass());
        }
        if (other.hasHideSuit()) {
          setHideSuit(other.getHideSuit());
        }
        if (other.hasLeadFinished()) {
          setLeadFinished(other.getLeadFinished());
        }
        if (other.hasMusicSwitch()) {
          setMusicSwitch(other.getMusicSwitch());
        }
        if (other.hasEffectSwitch()) {
          setEffectSwitch(other.getEffectSwitch());
        }
        if (other.hasMusicVolume()) {
          setMusicVolume(other.getMusicVolume());
        }
        if (other.hasEffectVolume()) {
          setEffectVolume(other.getEffectVolume());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hideHat_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hideGlass_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              hideSuit_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              leadFinished_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              musicSwitch_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              effectSwitch_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              musicVolume_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              effectVolume_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bool hideHat = 1;
      private boolean hideHat_ ;
      public boolean hasHideHat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getHideHat() {
        return hideHat_;
      }
      public Builder setHideHat(boolean value) {
        bitField0_ |= 0x00000001;
        hideHat_ = value;
        onChanged();
        return this;
      }
      public Builder clearHideHat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hideHat_ = false;
        onChanged();
        return this;
      }
      
      // optional bool hideGlass = 2;
      private boolean hideGlass_ ;
      public boolean hasHideGlass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getHideGlass() {
        return hideGlass_;
      }
      public Builder setHideGlass(boolean value) {
        bitField0_ |= 0x00000002;
        hideGlass_ = value;
        onChanged();
        return this;
      }
      public Builder clearHideGlass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hideGlass_ = false;
        onChanged();
        return this;
      }
      
      // optional bool hideSuit = 3;
      private boolean hideSuit_ ;
      public boolean hasHideSuit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getHideSuit() {
        return hideSuit_;
      }
      public Builder setHideSuit(boolean value) {
        bitField0_ |= 0x00000004;
        hideSuit_ = value;
        onChanged();
        return this;
      }
      public Builder clearHideSuit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hideSuit_ = false;
        onChanged();
        return this;
      }
      
      // optional bool leadFinished = 4;
      private boolean leadFinished_ ;
      public boolean hasLeadFinished() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getLeadFinished() {
        return leadFinished_;
      }
      public Builder setLeadFinished(boolean value) {
        bitField0_ |= 0x00000008;
        leadFinished_ = value;
        onChanged();
        return this;
      }
      public Builder clearLeadFinished() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leadFinished_ = false;
        onChanged();
        return this;
      }
      
      // optional bool musicSwitch = 5;
      private boolean musicSwitch_ ;
      public boolean hasMusicSwitch() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getMusicSwitch() {
        return musicSwitch_;
      }
      public Builder setMusicSwitch(boolean value) {
        bitField0_ |= 0x00000010;
        musicSwitch_ = value;
        onChanged();
        return this;
      }
      public Builder clearMusicSwitch() {
        bitField0_ = (bitField0_ & ~0x00000010);
        musicSwitch_ = false;
        onChanged();
        return this;
      }
      
      // optional bool effectSwitch = 6;
      private boolean effectSwitch_ ;
      public boolean hasEffectSwitch() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getEffectSwitch() {
        return effectSwitch_;
      }
      public Builder setEffectSwitch(boolean value) {
        bitField0_ |= 0x00000020;
        effectSwitch_ = value;
        onChanged();
        return this;
      }
      public Builder clearEffectSwitch() {
        bitField0_ = (bitField0_ & ~0x00000020);
        effectSwitch_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 musicVolume = 7;
      private int musicVolume_ ;
      public boolean hasMusicVolume() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getMusicVolume() {
        return musicVolume_;
      }
      public Builder setMusicVolume(int value) {
        bitField0_ |= 0x00000040;
        musicVolume_ = value;
        onChanged();
        return this;
      }
      public Builder clearMusicVolume() {
        bitField0_ = (bitField0_ & ~0x00000040);
        musicVolume_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 effectVolume = 8;
      private int effectVolume_ ;
      public boolean hasEffectVolume() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getEffectVolume() {
        return effectVolume_;
      }
      public Builder setEffectVolume(int value) {
        bitField0_ |= 0x00000080;
        effectVolume_ = value;
        onChanged();
        return this;
      }
      public Builder clearEffectVolume() {
        bitField0_ = (bitField0_ & ~0x00000080);
        effectVolume_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BceUserConfig)
    }
    
    static {
      defaultInstance = new BceUserConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BceUserConfig)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023BceUserConfig.proto\022 com.xinqihd.sns.g" +
      "ameserver.proto\"\261\001\n\rBceUserConfig\022\017\n\007hid" +
      "eHat\030\001 \001(\010\022\021\n\thideGlass\030\002 \001(\010\022\020\n\010hideSui" +
      "t\030\003 \001(\010\022\024\n\014leadFinished\030\004 \001(\010\022\023\n\013musicSw" +
      "itch\030\005 \001(\010\022\024\n\014effectSwitch\030\006 \001(\010\022\023\n\013musi" +
      "cVolume\030\007 \001(\005\022\024\n\014effectVolume\030\010 \001(\005B\024B\022X" +
      "inqiBceUserConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BceUserConfig_descriptor,
              new java.lang.String[] { "HideHat", "HideGlass", "HideSuit", "LeadFinished", "MusicSwitch", "EffectSwitch", "MusicVolume", "EffectVolume", },
              com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.class,
              com.xinqihd.sns.gameserver.proto.XinqiBceUserConfig.BceUserConfig.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
