// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BseFriendsInfo.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBseFriendsInfo {
  private XinqiBseFriendsInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BseFriendsInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 friBlood = 1;
    boolean hasFriBlood();
    int getFriBlood();
    
    // required int32 friThew = 2;
    boolean hasFriThew();
    int getFriThew();
    
    // required int32 friDamage = 3;
    boolean hasFriDamage();
    int getFriDamage();
    
    // required int32 friSkin = 4;
    boolean hasFriSkin();
    int getFriSkin();
    
    // required string friName = 5;
    boolean hasFriName();
    String getFriName();
  }
  public static final class BseFriendsInfo extends
      com.google.protobuf.GeneratedMessage
      implements BseFriendsInfoOrBuilder {
    // Use BseFriendsInfo.newBuilder() to construct.
    private BseFriendsInfo(Builder builder) {
      super(builder);
    }
    private BseFriendsInfo(boolean noInit) {}
    
    private static final BseFriendsInfo defaultInstance;
    public static BseFriendsInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public BseFriendsInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 friBlood = 1;
    public static final int FRIBLOOD_FIELD_NUMBER = 1;
    private int friBlood_;
    public boolean hasFriBlood() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getFriBlood() {
      return friBlood_;
    }
    
    // required int32 friThew = 2;
    public static final int FRITHEW_FIELD_NUMBER = 2;
    private int friThew_;
    public boolean hasFriThew() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFriThew() {
      return friThew_;
    }
    
    // required int32 friDamage = 3;
    public static final int FRIDAMAGE_FIELD_NUMBER = 3;
    private int friDamage_;
    public boolean hasFriDamage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getFriDamage() {
      return friDamage_;
    }
    
    // required int32 friSkin = 4;
    public static final int FRISKIN_FIELD_NUMBER = 4;
    private int friSkin_;
    public boolean hasFriSkin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getFriSkin() {
      return friSkin_;
    }
    
    // required string friName = 5;
    public static final int FRINAME_FIELD_NUMBER = 5;
    private java.lang.Object friName_;
    public boolean hasFriName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getFriName() {
      java.lang.Object ref = friName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          friName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFriNameBytes() {
      java.lang.Object ref = friName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        friName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      friBlood_ = 0;
      friThew_ = 0;
      friDamage_ = 0;
      friSkin_ = 0;
      friName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFriBlood()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriThew()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriDamage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriSkin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, friBlood_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, friThew_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, friDamage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, friSkin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getFriNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, friBlood_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, friThew_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, friDamage_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, friSkin_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFriNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        friBlood_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        friThew_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        friDamage_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        friSkin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        friName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo result = new com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friBlood_ = friBlood_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.friThew_ = friThew_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.friDamage_ = friDamage_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.friSkin_ = friSkin_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.friName_ = friName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.getDefaultInstance()) return this;
        if (other.hasFriBlood()) {
          setFriBlood(other.getFriBlood());
        }
        if (other.hasFriThew()) {
          setFriThew(other.getFriThew());
        }
        if (other.hasFriDamage()) {
          setFriDamage(other.getFriDamage());
        }
        if (other.hasFriSkin()) {
          setFriSkin(other.getFriSkin());
        }
        if (other.hasFriName()) {
          setFriName(other.getFriName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFriBlood()) {
          
          return false;
        }
        if (!hasFriThew()) {
          
          return false;
        }
        if (!hasFriDamage()) {
          
          return false;
        }
        if (!hasFriSkin()) {
          
          return false;
        }
        if (!hasFriName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              friBlood_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              friThew_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              friDamage_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              friSkin_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              friName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 friBlood = 1;
      private int friBlood_ ;
      public boolean hasFriBlood() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getFriBlood() {
        return friBlood_;
      }
      public Builder setFriBlood(int value) {
        bitField0_ |= 0x00000001;
        friBlood_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriBlood() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friBlood_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 friThew = 2;
      private int friThew_ ;
      public boolean hasFriThew() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFriThew() {
        return friThew_;
      }
      public Builder setFriThew(int value) {
        bitField0_ |= 0x00000002;
        friThew_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriThew() {
        bitField0_ = (bitField0_ & ~0x00000002);
        friThew_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 friDamage = 3;
      private int friDamage_ ;
      public boolean hasFriDamage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getFriDamage() {
        return friDamage_;
      }
      public Builder setFriDamage(int value) {
        bitField0_ |= 0x00000004;
        friDamage_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriDamage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        friDamage_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 friSkin = 4;
      private int friSkin_ ;
      public boolean hasFriSkin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getFriSkin() {
        return friSkin_;
      }
      public Builder setFriSkin(int value) {
        bitField0_ |= 0x00000008;
        friSkin_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriSkin() {
        bitField0_ = (bitField0_ & ~0x00000008);
        friSkin_ = 0;
        onChanged();
        return this;
      }
      
      // required string friName = 5;
      private java.lang.Object friName_ = "";
      public boolean hasFriName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getFriName() {
        java.lang.Object ref = friName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          friName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFriName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        friName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        friName_ = getDefaultInstance().getFriName();
        onChanged();
        return this;
      }
      void setFriName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        friName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BseFriendsInfo)
    }
    
    static {
      defaultInstance = new BseFriendsInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BseFriendsInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BseFriendsInfo.proto\022 com.xinqihd.sns." +
      "gameserver.proto\"h\n\016BseFriendsInfo\022\020\n\010fr" +
      "iBlood\030\001 \002(\005\022\017\n\007friThew\030\002 \002(\005\022\021\n\tfriDama" +
      "ge\030\003 \002(\005\022\017\n\007friSkin\030\004 \002(\005\022\017\n\007friName\030\005 \002" +
      "(\tB\025B\023XinqiBseFriendsInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BseFriendsInfo_descriptor,
              new java.lang.String[] { "FriBlood", "FriThew", "FriDamage", "FriSkin", "FriName", },
              com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseFriendsInfo.BseFriendsInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
