// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BseShop.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBseShop {
  private XinqiBseShop() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuyPriceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 price = 1;
    boolean hasPrice();
    int getPrice();
    
    // optional int32 validTimes = 2;
    boolean hasValidTimes();
    int getValidTimes();
  }
  public static final class BuyPrice extends
      com.google.protobuf.GeneratedMessage
      implements BuyPriceOrBuilder {
    // Use BuyPrice.newBuilder() to construct.
    private BuyPrice(Builder builder) {
      super(builder);
    }
    private BuyPrice(boolean noInit) {}
    
    private static final BuyPrice defaultInstance;
    public static BuyPrice getDefaultInstance() {
      return defaultInstance;
    }
    
    public BuyPrice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 price = 1;
    public static final int PRICE_FIELD_NUMBER = 1;
    private int price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPrice() {
      return price_;
    }
    
    // optional int32 validTimes = 2;
    public static final int VALIDTIMES_FIELD_NUMBER = 2;
    private int validTimes_;
    public boolean hasValidTimes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getValidTimes() {
      return validTimes_;
    }
    
    private void initFields() {
      price_ = 0;
      validTimes_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, price_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, validTimes_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, price_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, validTimes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        validTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice result = new com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.validTimes_ = validTimes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.getDefaultInstance()) return this;
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasValidTimes()) {
          setValidTimes(other.getValidTimes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              price_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              validTimes_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 price = 1;
      private int price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPrice() {
        return price_;
      }
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000001;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 validTimes = 2;
      private int validTimes_ ;
      public boolean hasValidTimes() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getValidTimes() {
        return validTimes_;
      }
      public Builder setValidTimes(int value) {
        bitField0_ |= 0x00000002;
        validTimes_ = value;
        onChanged();
        return this;
      }
      public Builder clearValidTimes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        validTimes_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BuyPrice)
    }
    
    static {
      defaultInstance = new BuyPrice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BuyPrice)
  }
  
  public interface ShopDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional uint32 type = 2;
    boolean hasType();
    int getType();
    
    // optional string info = 3;
    boolean hasInfo();
    String getInfo();
    
    // optional string propInfoId = 4;
    boolean hasPropInfoId();
    String getPropInfoId();
    
    // optional int32 level = 5;
    boolean hasLevel();
    int getLevel();
    
    // optional uint32 goldTye = 6;
    boolean hasGoldTye();
    int getGoldTye();
    
    // repeated .com.xinqihd.sns.gameserver.proto.BuyPrice buyPrices = 7;
    java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> 
        getBuyPricesList();
    com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice getBuyPrices(int index);
    int getBuyPricesCount();
    java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder> 
        getBuyPricesOrBuilderList();
    com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder getBuyPricesOrBuilder(
        int index);
    
    // optional bool banded = 8;
    boolean hasBanded();
    boolean getBanded();
    
    // optional uint32 discount = 9 [default = 100];
    boolean hasDiscount();
    int getDiscount();
    
    // optional bool sell = 10;
    boolean hasSell();
    boolean getSell();
    
    // optional int32 hot = 11;
    boolean hasHot();
    int getHot();
    
    // optional int32 limitCount = 12;
    boolean hasLimitCount();
    int getLimitCount();
    
    // optional int32 limitGroup = 13;
    boolean hasLimitGroup();
    int getLimitGroup();
    
    // optional int32 shopId = 14;
    boolean hasShopId();
    int getShopId();
  }
  public static final class ShopData extends
      com.google.protobuf.GeneratedMessage
      implements ShopDataOrBuilder {
    // Use ShopData.newBuilder() to construct.
    private ShopData(Builder builder) {
      super(builder);
    }
    private ShopData(boolean noInit) {}
    
    private static final ShopData defaultInstance;
    public static ShopData getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShopData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_ShopData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_ShopData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getType() {
      return type_;
    }
    
    // optional string info = 3;
    public static final int INFO_FIELD_NUMBER = 3;
    private java.lang.Object info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          info_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string propInfoId = 4;
    public static final int PROPINFOID_FIELD_NUMBER = 4;
    private java.lang.Object propInfoId_;
    public boolean hasPropInfoId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPropInfoId() {
      java.lang.Object ref = propInfoId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propInfoId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropInfoIdBytes() {
      java.lang.Object ref = propInfoId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propInfoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 level = 5;
    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getLevel() {
      return level_;
    }
    
    // optional uint32 goldTye = 6;
    public static final int GOLDTYE_FIELD_NUMBER = 6;
    private int goldTye_;
    public boolean hasGoldTye() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getGoldTye() {
      return goldTye_;
    }
    
    // repeated .com.xinqihd.sns.gameserver.proto.BuyPrice buyPrices = 7;
    public static final int BUYPRICES_FIELD_NUMBER = 7;
    private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> buyPrices_;
    public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> getBuyPricesList() {
      return buyPrices_;
    }
    public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder> 
        getBuyPricesOrBuilderList() {
      return buyPrices_;
    }
    public int getBuyPricesCount() {
      return buyPrices_.size();
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice getBuyPrices(int index) {
      return buyPrices_.get(index);
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder getBuyPricesOrBuilder(
        int index) {
      return buyPrices_.get(index);
    }
    
    // optional bool banded = 8;
    public static final int BANDED_FIELD_NUMBER = 8;
    private boolean banded_;
    public boolean hasBanded() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getBanded() {
      return banded_;
    }
    
    // optional uint32 discount = 9 [default = 100];
    public static final int DISCOUNT_FIELD_NUMBER = 9;
    private int discount_;
    public boolean hasDiscount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getDiscount() {
      return discount_;
    }
    
    // optional bool sell = 10;
    public static final int SELL_FIELD_NUMBER = 10;
    private boolean sell_;
    public boolean hasSell() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getSell() {
      return sell_;
    }
    
    // optional int32 hot = 11;
    public static final int HOT_FIELD_NUMBER = 11;
    private int hot_;
    public boolean hasHot() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getHot() {
      return hot_;
    }
    
    // optional int32 limitCount = 12;
    public static final int LIMITCOUNT_FIELD_NUMBER = 12;
    private int limitCount_;
    public boolean hasLimitCount() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getLimitCount() {
      return limitCount_;
    }
    
    // optional int32 limitGroup = 13;
    public static final int LIMITGROUP_FIELD_NUMBER = 13;
    private int limitGroup_;
    public boolean hasLimitGroup() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getLimitGroup() {
      return limitGroup_;
    }
    
    // optional int32 shopId = 14;
    public static final int SHOPID_FIELD_NUMBER = 14;
    private int shopId_;
    public boolean hasShopId() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getShopId() {
      return shopId_;
    }
    
    private void initFields() {
      id_ = "";
      type_ = 0;
      info_ = "";
      propInfoId_ = "";
      level_ = 0;
      goldTye_ = 0;
      buyPrices_ = java.util.Collections.emptyList();
      banded_ = false;
      discount_ = 100;
      sell_ = false;
      hot_ = 0;
      limitCount_ = 0;
      limitGroup_ = 0;
      shopId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPropInfoIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, goldTye_);
      }
      for (int i = 0; i < buyPrices_.size(); i++) {
        output.writeMessage(7, buyPrices_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(8, banded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, discount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(10, sell_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(11, hot_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(12, limitCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(13, limitGroup_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(14, shopId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPropInfoIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, goldTye_);
      }
      for (int i = 0; i < buyPrices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, buyPrices_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, banded_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, discount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, sell_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, hot_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, limitCount_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, limitGroup_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, shopId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_ShopData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_ShopData_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuyPricesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        propInfoId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        goldTye_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (buyPricesBuilder_ == null) {
          buyPrices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          buyPricesBuilder_.clear();
        }
        banded_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        discount_ = 100;
        bitField0_ = (bitField0_ & ~0x00000100);
        sell_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        hot_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        limitCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        limitGroup_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        shopId_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData result = new com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.propInfoId_ = propInfoId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.goldTye_ = goldTye_;
        if (buyPricesBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            buyPrices_ = java.util.Collections.unmodifiableList(buyPrices_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.buyPrices_ = buyPrices_;
        } else {
          result.buyPrices_ = buyPricesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.banded_ = banded_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.discount_ = discount_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.sell_ = sell_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.hot_ = hot_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.limitCount_ = limitCount_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.limitGroup_ = limitGroup_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.shopId_ = shopId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasInfo()) {
          setInfo(other.getInfo());
        }
        if (other.hasPropInfoId()) {
          setPropInfoId(other.getPropInfoId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasGoldTye()) {
          setGoldTye(other.getGoldTye());
        }
        if (buyPricesBuilder_ == null) {
          if (!other.buyPrices_.isEmpty()) {
            if (buyPrices_.isEmpty()) {
              buyPrices_ = other.buyPrices_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureBuyPricesIsMutable();
              buyPrices_.addAll(other.buyPrices_);
            }
            onChanged();
          }
        } else {
          if (!other.buyPrices_.isEmpty()) {
            if (buyPricesBuilder_.isEmpty()) {
              buyPricesBuilder_.dispose();
              buyPricesBuilder_ = null;
              buyPrices_ = other.buyPrices_;
              bitField0_ = (bitField0_ & ~0x00000040);
              buyPricesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBuyPricesFieldBuilder() : null;
            } else {
              buyPricesBuilder_.addAllMessages(other.buyPrices_);
            }
          }
        }
        if (other.hasBanded()) {
          setBanded(other.getBanded());
        }
        if (other.hasDiscount()) {
          setDiscount(other.getDiscount());
        }
        if (other.hasSell()) {
          setSell(other.getSell());
        }
        if (other.hasHot()) {
          setHot(other.getHot());
        }
        if (other.hasLimitCount()) {
          setLimitCount(other.getLimitCount());
        }
        if (other.hasLimitGroup()) {
          setLimitGroup(other.getLimitGroup());
        }
        if (other.hasShopId()) {
          setShopId(other.getShopId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              info_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              propInfoId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              goldTye_ = input.readUInt32();
              break;
            }
            case 58: {
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder subBuilder = com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBuyPrices(subBuilder.buildPartial());
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              banded_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              discount_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              sell_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              hot_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              limitCount_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              limitGroup_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              shopId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional uint32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // optional string info = 3;
      private java.lang.Object info_ = "";
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        info_ = value;
        onChanged();
        return this;
      }
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      void setInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        info_ = value;
        onChanged();
      }
      
      // optional string propInfoId = 4;
      private java.lang.Object propInfoId_ = "";
      public boolean hasPropInfoId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPropInfoId() {
        java.lang.Object ref = propInfoId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propInfoId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropInfoId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        propInfoId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropInfoId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        propInfoId_ = getDefaultInstance().getPropInfoId();
        onChanged();
        return this;
      }
      void setPropInfoId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        propInfoId_ = value;
        onChanged();
      }
      
      // optional int32 level = 5;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 goldTye = 6;
      private int goldTye_ ;
      public boolean hasGoldTye() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getGoldTye() {
        return goldTye_;
      }
      public Builder setGoldTye(int value) {
        bitField0_ |= 0x00000020;
        goldTye_ = value;
        onChanged();
        return this;
      }
      public Builder clearGoldTye() {
        bitField0_ = (bitField0_ & ~0x00000020);
        goldTye_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.xinqihd.sns.gameserver.proto.BuyPrice buyPrices = 7;
      private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> buyPrices_ =
        java.util.Collections.emptyList();
      private void ensureBuyPricesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          buyPrices_ = new java.util.ArrayList<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice>(buyPrices_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder> buyPricesBuilder_;
      
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> getBuyPricesList() {
        if (buyPricesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buyPrices_);
        } else {
          return buyPricesBuilder_.getMessageList();
        }
      }
      public int getBuyPricesCount() {
        if (buyPricesBuilder_ == null) {
          return buyPrices_.size();
        } else {
          return buyPricesBuilder_.getCount();
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice getBuyPrices(int index) {
        if (buyPricesBuilder_ == null) {
          return buyPrices_.get(index);
        } else {
          return buyPricesBuilder_.getMessage(index);
        }
      }
      public Builder setBuyPrices(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice value) {
        if (buyPricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuyPricesIsMutable();
          buyPrices_.set(index, value);
          onChanged();
        } else {
          buyPricesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBuyPrices(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder builderForValue) {
        if (buyPricesBuilder_ == null) {
          ensureBuyPricesIsMutable();
          buyPrices_.set(index, builderForValue.build());
          onChanged();
        } else {
          buyPricesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBuyPrices(com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice value) {
        if (buyPricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuyPricesIsMutable();
          buyPrices_.add(value);
          onChanged();
        } else {
          buyPricesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBuyPrices(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice value) {
        if (buyPricesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBuyPricesIsMutable();
          buyPrices_.add(index, value);
          onChanged();
        } else {
          buyPricesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBuyPrices(
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder builderForValue) {
        if (buyPricesBuilder_ == null) {
          ensureBuyPricesIsMutable();
          buyPrices_.add(builderForValue.build());
          onChanged();
        } else {
          buyPricesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBuyPrices(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder builderForValue) {
        if (buyPricesBuilder_ == null) {
          ensureBuyPricesIsMutable();
          buyPrices_.add(index, builderForValue.build());
          onChanged();
        } else {
          buyPricesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBuyPrices(
          java.lang.Iterable<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice> values) {
        if (buyPricesBuilder_ == null) {
          ensureBuyPricesIsMutable();
          super.addAll(values, buyPrices_);
          onChanged();
        } else {
          buyPricesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBuyPrices() {
        if (buyPricesBuilder_ == null) {
          buyPrices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          buyPricesBuilder_.clear();
        }
        return this;
      }
      public Builder removeBuyPrices(int index) {
        if (buyPricesBuilder_ == null) {
          ensureBuyPricesIsMutable();
          buyPrices_.remove(index);
          onChanged();
        } else {
          buyPricesBuilder_.remove(index);
        }
        return this;
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder getBuyPricesBuilder(
          int index) {
        return getBuyPricesFieldBuilder().getBuilder(index);
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder getBuyPricesOrBuilder(
          int index) {
        if (buyPricesBuilder_ == null) {
          return buyPrices_.get(index);  } else {
          return buyPricesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder> 
           getBuyPricesOrBuilderList() {
        if (buyPricesBuilder_ != null) {
          return buyPricesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buyPrices_);
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder addBuyPricesBuilder() {
        return getBuyPricesFieldBuilder().addBuilder(
            com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.getDefaultInstance());
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder addBuyPricesBuilder(
          int index) {
        return getBuyPricesFieldBuilder().addBuilder(
            index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.getDefaultInstance());
      }
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder> 
           getBuyPricesBuilderList() {
        return getBuyPricesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder> 
          getBuyPricesFieldBuilder() {
        if (buyPricesBuilder_ == null) {
          buyPricesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPriceOrBuilder>(
                  buyPrices_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          buyPrices_ = null;
        }
        return buyPricesBuilder_;
      }
      
      // optional bool banded = 8;
      private boolean banded_ ;
      public boolean hasBanded() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public boolean getBanded() {
        return banded_;
      }
      public Builder setBanded(boolean value) {
        bitField0_ |= 0x00000080;
        banded_ = value;
        onChanged();
        return this;
      }
      public Builder clearBanded() {
        bitField0_ = (bitField0_ & ~0x00000080);
        banded_ = false;
        onChanged();
        return this;
      }
      
      // optional uint32 discount = 9 [default = 100];
      private int discount_ = 100;
      public boolean hasDiscount() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getDiscount() {
        return discount_;
      }
      public Builder setDiscount(int value) {
        bitField0_ |= 0x00000100;
        discount_ = value;
        onChanged();
        return this;
      }
      public Builder clearDiscount() {
        bitField0_ = (bitField0_ & ~0x00000100);
        discount_ = 100;
        onChanged();
        return this;
      }
      
      // optional bool sell = 10;
      private boolean sell_ ;
      public boolean hasSell() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public boolean getSell() {
        return sell_;
      }
      public Builder setSell(boolean value) {
        bitField0_ |= 0x00000200;
        sell_ = value;
        onChanged();
        return this;
      }
      public Builder clearSell() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sell_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 hot = 11;
      private int hot_ ;
      public boolean hasHot() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getHot() {
        return hot_;
      }
      public Builder setHot(int value) {
        bitField0_ |= 0x00000400;
        hot_ = value;
        onChanged();
        return this;
      }
      public Builder clearHot() {
        bitField0_ = (bitField0_ & ~0x00000400);
        hot_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 limitCount = 12;
      private int limitCount_ ;
      public boolean hasLimitCount() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getLimitCount() {
        return limitCount_;
      }
      public Builder setLimitCount(int value) {
        bitField0_ |= 0x00000800;
        limitCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearLimitCount() {
        bitField0_ = (bitField0_ & ~0x00000800);
        limitCount_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 limitGroup = 13;
      private int limitGroup_ ;
      public boolean hasLimitGroup() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getLimitGroup() {
        return limitGroup_;
      }
      public Builder setLimitGroup(int value) {
        bitField0_ |= 0x00001000;
        limitGroup_ = value;
        onChanged();
        return this;
      }
      public Builder clearLimitGroup() {
        bitField0_ = (bitField0_ & ~0x00001000);
        limitGroup_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 shopId = 14;
      private int shopId_ ;
      public boolean hasShopId() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getShopId() {
        return shopId_;
      }
      public Builder setShopId(int value) {
        bitField0_ |= 0x00002000;
        shopId_ = value;
        onChanged();
        return this;
      }
      public Builder clearShopId() {
        bitField0_ = (bitField0_ & ~0x00002000);
        shopId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.ShopData)
    }
    
    static {
      defaultInstance = new ShopData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.ShopData)
  }
  
  public interface BseShopOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.xinqihd.sns.gameserver.proto.ShopData shops = 1;
    java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> 
        getShopsList();
    com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData getShops(int index);
    int getShopsCount();
    java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder> 
        getShopsOrBuilderList();
    com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder getShopsOrBuilder(
        int index);
  }
  public static final class BseShop extends
      com.google.protobuf.GeneratedMessage
      implements BseShopOrBuilder {
    // Use BseShop.newBuilder() to construct.
    private BseShop(Builder builder) {
      super(builder);
    }
    private BseShop(boolean noInit) {}
    
    private static final BseShop defaultInstance;
    public static BseShop getDefaultInstance() {
      return defaultInstance;
    }
    
    public BseShop getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BseShop_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BseShop_fieldAccessorTable;
    }
    
    // repeated .com.xinqihd.sns.gameserver.proto.ShopData shops = 1;
    public static final int SHOPS_FIELD_NUMBER = 1;
    private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> shops_;
    public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> getShopsList() {
      return shops_;
    }
    public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder> 
        getShopsOrBuilderList() {
      return shops_;
    }
    public int getShopsCount() {
      return shops_.size();
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData getShops(int index) {
      return shops_.get(index);
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder getShopsOrBuilder(
        int index) {
      return shops_.get(index);
    }
    
    private void initFields() {
      shops_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < shops_.size(); i++) {
        output.writeMessage(1, shops_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < shops_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, shops_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShopOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BseShop_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.internal_static_com_xinqihd_sns_gameserver_proto_BseShop_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getShopsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (shopsBuilder_ == null) {
          shops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          shopsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop result = new com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop(this);
        int from_bitField0_ = bitField0_;
        if (shopsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            shops_ = java.util.Collections.unmodifiableList(shops_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.shops_ = shops_;
        } else {
          result.shops_ = shopsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.getDefaultInstance()) return this;
        if (shopsBuilder_ == null) {
          if (!other.shops_.isEmpty()) {
            if (shops_.isEmpty()) {
              shops_ = other.shops_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureShopsIsMutable();
              shops_.addAll(other.shops_);
            }
            onChanged();
          }
        } else {
          if (!other.shops_.isEmpty()) {
            if (shopsBuilder_.isEmpty()) {
              shopsBuilder_.dispose();
              shopsBuilder_ = null;
              shops_ = other.shops_;
              bitField0_ = (bitField0_ & ~0x00000001);
              shopsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getShopsFieldBuilder() : null;
            } else {
              shopsBuilder_.addAllMessages(other.shops_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder subBuilder = com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addShops(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.xinqihd.sns.gameserver.proto.ShopData shops = 1;
      private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> shops_ =
        java.util.Collections.emptyList();
      private void ensureShopsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          shops_ = new java.util.ArrayList<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData>(shops_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder> shopsBuilder_;
      
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> getShopsList() {
        if (shopsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(shops_);
        } else {
          return shopsBuilder_.getMessageList();
        }
      }
      public int getShopsCount() {
        if (shopsBuilder_ == null) {
          return shops_.size();
        } else {
          return shopsBuilder_.getCount();
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData getShops(int index) {
        if (shopsBuilder_ == null) {
          return shops_.get(index);
        } else {
          return shopsBuilder_.getMessage(index);
        }
      }
      public Builder setShops(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData value) {
        if (shopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopsIsMutable();
          shops_.set(index, value);
          onChanged();
        } else {
          shopsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setShops(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder builderForValue) {
        if (shopsBuilder_ == null) {
          ensureShopsIsMutable();
          shops_.set(index, builderForValue.build());
          onChanged();
        } else {
          shopsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addShops(com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData value) {
        if (shopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopsIsMutable();
          shops_.add(value);
          onChanged();
        } else {
          shopsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addShops(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData value) {
        if (shopsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureShopsIsMutable();
          shops_.add(index, value);
          onChanged();
        } else {
          shopsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addShops(
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder builderForValue) {
        if (shopsBuilder_ == null) {
          ensureShopsIsMutable();
          shops_.add(builderForValue.build());
          onChanged();
        } else {
          shopsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addShops(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder builderForValue) {
        if (shopsBuilder_ == null) {
          ensureShopsIsMutable();
          shops_.add(index, builderForValue.build());
          onChanged();
        } else {
          shopsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllShops(
          java.lang.Iterable<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData> values) {
        if (shopsBuilder_ == null) {
          ensureShopsIsMutable();
          super.addAll(values, shops_);
          onChanged();
        } else {
          shopsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearShops() {
        if (shopsBuilder_ == null) {
          shops_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          shopsBuilder_.clear();
        }
        return this;
      }
      public Builder removeShops(int index) {
        if (shopsBuilder_ == null) {
          ensureShopsIsMutable();
          shops_.remove(index);
          onChanged();
        } else {
          shopsBuilder_.remove(index);
        }
        return this;
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder getShopsBuilder(
          int index) {
        return getShopsFieldBuilder().getBuilder(index);
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder getShopsOrBuilder(
          int index) {
        if (shopsBuilder_ == null) {
          return shops_.get(index);  } else {
          return shopsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder> 
           getShopsOrBuilderList() {
        if (shopsBuilder_ != null) {
          return shopsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(shops_);
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder addShopsBuilder() {
        return getShopsFieldBuilder().addBuilder(
            com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.getDefaultInstance());
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder addShopsBuilder(
          int index) {
        return getShopsFieldBuilder().addBuilder(
            index, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.getDefaultInstance());
      }
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder> 
           getShopsBuilderList() {
        return getShopsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder> 
          getShopsFieldBuilder() {
        if (shopsBuilder_ == null) {
          shopsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopDataOrBuilder>(
                  shops_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          shops_ = null;
        }
        return shopsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BseShop)
    }
    
    static {
      defaultInstance = new BseShop(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BseShop)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_ShopData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_ShopData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BseShop_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BseShop_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBseShop.proto\022 com.xinqihd.sns.gameser" +
      "ver.proto\"-\n\010BuyPrice\022\r\n\005price\030\001 \001(\005\022\022\n\n" +
      "validTimes\030\002 \001(\005\"\237\002\n\010ShopData\022\n\n\002id\030\001 \001(" +
      "\t\022\014\n\004type\030\002 \001(\r\022\014\n\004info\030\003 \001(\t\022\022\n\npropInf" +
      "oId\030\004 \001(\t\022\r\n\005level\030\005 \001(\005\022\017\n\007goldTye\030\006 \001(" +
      "\r\022=\n\tbuyPrices\030\007 \003(\0132*.com.xinqihd.sns.g" +
      "ameserver.proto.BuyPrice\022\016\n\006banded\030\010 \001(\010" +
      "\022\025\n\010discount\030\t \001(\r:\003100\022\014\n\004sell\030\n \001(\010\022\013\n" +
      "\003hot\030\013 \001(\005\022\022\n\nlimitCount\030\014 \001(\005\022\022\n\nlimitG" +
      "roup\030\r \001(\005\022\016\n\006shopId\030\016 \001(\005\"D\n\007BseShop\0229\n",
      "\005shops\030\001 \003(\0132*.com.xinqihd.sns.gameserve" +
      "r.proto.ShopDataB\016B\014XinqiBseShop"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BuyPrice_descriptor,
              new java.lang.String[] { "Price", "ValidTimes", },
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BuyPrice.Builder.class);
          internal_static_com_xinqihd_sns_gameserver_proto_ShopData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_xinqihd_sns_gameserver_proto_ShopData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_ShopData_descriptor,
              new java.lang.String[] { "Id", "Type", "Info", "PropInfoId", "Level", "GoldTye", "BuyPrices", "Banded", "Discount", "Sell", "Hot", "LimitCount", "LimitGroup", "ShopId", },
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.ShopData.Builder.class);
          internal_static_com_xinqihd_sns_gameserver_proto_BseShop_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_xinqihd_sns_gameserver_proto_BseShop_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BseShop_descriptor,
              new java.lang.String[] { "Shops", },
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseShop.BseShop.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
