// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BcePropDataQuery.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBcePropDataQuery {
  private XinqiBcePropDataQuery() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BcePropDataQueryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string giftstr = 1;
    boolean hasGiftstr();
    String getGiftstr();
    
    // optional .com.xinqihd.sns.gameserver.proto.Gift gift = 2;
    boolean hasGift();
    com.xinqihd.sns.gameserver.proto.XinqiGift.Gift getGift();
    com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder getGiftOrBuilder();
    
    // optional string weaponid = 3;
    boolean hasWeaponid();
    String getWeaponid();
    
    // optional int32 pew = 4;
    boolean hasPew();
    int getPew();
    
    // optional string userid = 5;
    boolean hasUserid();
    String getUserid();
  }
  public static final class BcePropDataQuery extends
      com.google.protobuf.GeneratedMessage
      implements BcePropDataQueryOrBuilder {
    // Use BcePropDataQuery.newBuilder() to construct.
    private BcePropDataQuery(Builder builder) {
      super(builder);
    }
    private BcePropDataQuery(boolean noInit) {}
    
    private static final BcePropDataQuery defaultInstance;
    public static BcePropDataQuery getDefaultInstance() {
      return defaultInstance;
    }
    
    public BcePropDataQuery getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string giftstr = 1;
    public static final int GIFTSTR_FIELD_NUMBER = 1;
    private java.lang.Object giftstr_;
    public boolean hasGiftstr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGiftstr() {
      java.lang.Object ref = giftstr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          giftstr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGiftstrBytes() {
      java.lang.Object ref = giftstr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        giftstr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .com.xinqihd.sns.gameserver.proto.Gift gift = 2;
    public static final int GIFT_FIELD_NUMBER = 2;
    private com.xinqihd.sns.gameserver.proto.XinqiGift.Gift gift_;
    public boolean hasGift() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.xinqihd.sns.gameserver.proto.XinqiGift.Gift getGift() {
      return gift_;
    }
    public com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder getGiftOrBuilder() {
      return gift_;
    }
    
    // optional string weaponid = 3;
    public static final int WEAPONID_FIELD_NUMBER = 3;
    private java.lang.Object weaponid_;
    public boolean hasWeaponid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getWeaponid() {
      java.lang.Object ref = weaponid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          weaponid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWeaponidBytes() {
      java.lang.Object ref = weaponid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        weaponid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 pew = 4;
    public static final int PEW_FIELD_NUMBER = 4;
    private int pew_;
    public boolean hasPew() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPew() {
      return pew_;
    }
    
    // optional string userid = 5;
    public static final int USERID_FIELD_NUMBER = 5;
    private java.lang.Object userid_;
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUserid() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUseridBytes() {
      java.lang.Object ref = userid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      giftstr_ = "";
      gift_ = com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.getDefaultInstance();
      weaponid_ = "";
      pew_ = 0;
      userid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasGift()) {
        if (!getGift().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGiftstrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, gift_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getWeaponidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pew_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUseridBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGiftstrBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, gift_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getWeaponidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pew_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUseridBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGiftFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        giftstr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (giftBuilder_ == null) {
          gift_ = com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.getDefaultInstance();
        } else {
          giftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        weaponid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pew_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        userid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery build() {
        com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery result = new com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.giftstr_ = giftstr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (giftBuilder_ == null) {
          result.gift_ = gift_;
        } else {
          result.gift_ = giftBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.weaponid_ = weaponid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pew_ = pew_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userid_ = userid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.getDefaultInstance()) return this;
        if (other.hasGiftstr()) {
          setGiftstr(other.getGiftstr());
        }
        if (other.hasGift()) {
          mergeGift(other.getGift());
        }
        if (other.hasWeaponid()) {
          setWeaponid(other.getWeaponid());
        }
        if (other.hasPew()) {
          setPew(other.getPew());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasGift()) {
          if (!getGift().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              giftstr_ = input.readBytes();
              break;
            }
            case 18: {
              com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder subBuilder = com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.newBuilder();
              if (hasGift()) {
                subBuilder.mergeFrom(getGift());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGift(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              weaponid_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pew_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              userid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string giftstr = 1;
      private java.lang.Object giftstr_ = "";
      public boolean hasGiftstr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGiftstr() {
        java.lang.Object ref = giftstr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          giftstr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGiftstr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        giftstr_ = value;
        onChanged();
        return this;
      }
      public Builder clearGiftstr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        giftstr_ = getDefaultInstance().getGiftstr();
        onChanged();
        return this;
      }
      void setGiftstr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        giftstr_ = value;
        onChanged();
      }
      
      // optional .com.xinqihd.sns.gameserver.proto.Gift gift = 2;
      private com.xinqihd.sns.gameserver.proto.XinqiGift.Gift gift_ = com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiGift.Gift, com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder, com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder> giftBuilder_;
      public boolean hasGift() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.xinqihd.sns.gameserver.proto.XinqiGift.Gift getGift() {
        if (giftBuilder_ == null) {
          return gift_;
        } else {
          return giftBuilder_.getMessage();
        }
      }
      public Builder setGift(com.xinqihd.sns.gameserver.proto.XinqiGift.Gift value) {
        if (giftBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gift_ = value;
          onChanged();
        } else {
          giftBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setGift(
          com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder builderForValue) {
        if (giftBuilder_ == null) {
          gift_ = builderForValue.build();
          onChanged();
        } else {
          giftBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeGift(com.xinqihd.sns.gameserver.proto.XinqiGift.Gift value) {
        if (giftBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              gift_ != com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.getDefaultInstance()) {
            gift_ =
              com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.newBuilder(gift_).mergeFrom(value).buildPartial();
          } else {
            gift_ = value;
          }
          onChanged();
        } else {
          giftBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearGift() {
        if (giftBuilder_ == null) {
          gift_ = com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.getDefaultInstance();
          onChanged();
        } else {
          giftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder getGiftBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGiftFieldBuilder().getBuilder();
      }
      public com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder getGiftOrBuilder() {
        if (giftBuilder_ != null) {
          return giftBuilder_.getMessageOrBuilder();
        } else {
          return gift_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiGift.Gift, com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder, com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder> 
          getGiftFieldBuilder() {
        if (giftBuilder_ == null) {
          giftBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.xinqihd.sns.gameserver.proto.XinqiGift.Gift, com.xinqihd.sns.gameserver.proto.XinqiGift.Gift.Builder, com.xinqihd.sns.gameserver.proto.XinqiGift.GiftOrBuilder>(
                  gift_,
                  getParentForChildren(),
                  isClean());
          gift_ = null;
        }
        return giftBuilder_;
      }
      
      // optional string weaponid = 3;
      private java.lang.Object weaponid_ = "";
      public boolean hasWeaponid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getWeaponid() {
        java.lang.Object ref = weaponid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          weaponid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWeaponid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        weaponid_ = value;
        onChanged();
        return this;
      }
      public Builder clearWeaponid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weaponid_ = getDefaultInstance().getWeaponid();
        onChanged();
        return this;
      }
      void setWeaponid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        weaponid_ = value;
        onChanged();
      }
      
      // optional int32 pew = 4;
      private int pew_ ;
      public boolean hasPew() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPew() {
        return pew_;
      }
      public Builder setPew(int value) {
        bitField0_ |= 0x00000008;
        pew_ = value;
        onChanged();
        return this;
      }
      public Builder clearPew() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pew_ = 0;
        onChanged();
        return this;
      }
      
      // optional string userid = 5;
      private java.lang.Object userid_ = "";
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUserid() {
        java.lang.Object ref = userid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userid_ = getDefaultInstance().getUserid();
        onChanged();
        return this;
      }
      void setUserid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        userid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BcePropDataQuery)
    }
    
    static {
      defaultInstance = new BcePropDataQuery(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BcePropDataQuery)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BcePropDataQuery.proto\022 com.xinqihd.sn" +
      "s.gameserver.proto\032\nGift.proto\"\210\001\n\020BcePr" +
      "opDataQuery\022\017\n\007giftstr\030\001 \001(\t\0224\n\004gift\030\002 \001" +
      "(\0132&.com.xinqihd.sns.gameserver.proto.Gi" +
      "ft\022\020\n\010weaponid\030\003 \001(\t\022\013\n\003pew\030\004 \001(\005\022\016\n\006use" +
      "rid\030\005 \001(\tB\027B\025XinqiBcePropDataQuery"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BcePropDataQuery_descriptor,
              new java.lang.String[] { "Giftstr", "Gift", "Weaponid", "Pew", "Userid", },
              com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.class,
              com.xinqihd.sns.gameserver.proto.XinqiBcePropDataQuery.BcePropDataQuery.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xinqihd.sns.gameserver.proto.XinqiGift.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
