-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BceActionLimitQuery_pb', package.seeall)


local BCEACTIONLIMITQUERY = protobuf.Descriptor();
local BCEACTIONLIMITQUERY_ACTION_FIELD = protobuf.FieldDescriptor();

BCEACTIONLIMITQUERY_ACTION_FIELD.name = "action"
BCEACTIONLIMITQUERY_ACTION_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceActionLimitQuery.action"
BCEACTIONLIMITQUERY_ACTION_FIELD.number = 1
BCEACTIONLIMITQUERY_ACTION_FIELD.index = 0
BCEACTIONLIMITQUERY_ACTION_FIELD.label = 2
BCEACTIONLIMITQUERY_ACTION_FIELD.has_default_value = false
BCEACTIONLIMITQUERY_ACTION_FIELD.default_value = 0
BCEACTIONLIMITQUERY_ACTION_FIELD.type = 13
BCEACTIONLIMITQUERY_ACTION_FIELD.cpp_type = 3

BCEACTIONLIMITQUERY.name = "BceActionLimitQuery"
BCEACTIONLIMITQUERY.full_name = ".com.xinqihd.sns.gameserver.proto.BceActionLimitQuery"
BCEACTIONLIMITQUERY.nested_types = {}
BCEACTIONLIMITQUERY.enum_types = {}
BCEACTIONLIMITQUERY.fields = {BCEACTIONLIMITQUERY_ACTION_FIELD}
BCEACTIONLIMITQUERY.is_extendable = false
BCEACTIONLIMITQUERY.extensions = {}

BceActionLimitQuery = protobuf.Message(BCEACTIONLIMITQUERY)
_G.BCEACTIONLIMITQUERY_PB_BCEACTIONLIMITQUERY = BCEACTIONLIMITQUERY

