-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BceGuildApplyList_pb', package.seeall)


local BCEGUILDAPPLYLIST = protobuf.Descriptor();

BCEGUILDAPPLYLIST.name = "BceGuildApplyList"
BCEGUILDAPPLYLIST.full_name = ".com.xinqihd.sns.gameserver.proto.BceGuildApplyList"
BCEGUILDAPPLYLIST.nested_types = {}
BCEGUILDAPPLYLIST.enum_types = {}
BCEGUILDAPPLYLIST.fields = {}
BCEGUILDAPPLYLIST.is_extendable = false
BCEGUILDAPPLYLIST.extensions = {}

BceGuildApplyList = protobuf.Message(BCEGUILDAPPLYLIST)
_G.BCEGUILDAPPLYLIST_PB_BCEGUILDAPPLYLIST = BCEGUILDAPPLYLIST

