-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BceGuildList_pb', package.seeall)


local BCEGUILDLIST = protobuf.Descriptor();
local BCEGUILDLIST_STARTPOS_FIELD = protobuf.FieldDescriptor();
local BCEGUILDLIST_COUNT_FIELD = protobuf.FieldDescriptor();

BCEGUILDLIST_STARTPOS_FIELD.name = "startpos"
BCEGUILDLIST_STARTPOS_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceGuildList.startpos"
BCEGUILDLIST_STARTPOS_FIELD.number = 1
BCEGUILDLIST_STARTPOS_FIELD.index = 0
BCEGUILDLIST_STARTPOS_FIELD.label = 1
BCEGUILDLIST_STARTPOS_FIELD.has_default_value = true
BCEGUILDLIST_STARTPOS_FIELD.default_value = 0
BCEGUILDLIST_STARTPOS_FIELD.type = 5
BCEGUILDLIST_STARTPOS_FIELD.cpp_type = 1

BCEGUILDLIST_COUNT_FIELD.name = "count"
BCEGUILDLIST_COUNT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceGuildList.count"
BCEGUILDLIST_COUNT_FIELD.number = 2
BCEGUILDLIST_COUNT_FIELD.index = 1
BCEGUILDLIST_COUNT_FIELD.label = 1
BCEGUILDLIST_COUNT_FIELD.has_default_value = true
BCEGUILDLIST_COUNT_FIELD.default_value = -1
BCEGUILDLIST_COUNT_FIELD.type = 5
BCEGUILDLIST_COUNT_FIELD.cpp_type = 1

BCEGUILDLIST.name = "BceGuildList"
BCEGUILDLIST.full_name = ".com.xinqihd.sns.gameserver.proto.BceGuildList"
BCEGUILDLIST.nested_types = {}
BCEGUILDLIST.enum_types = {}
BCEGUILDLIST.fields = {BCEGUILDLIST_STARTPOS_FIELD, BCEGUILDLIST_COUNT_FIELD}
BCEGUILDLIST.is_extendable = false
BCEGUILDLIST.extensions = {}

BceGuildList = protobuf.Message(BCEGUILDLIST)
_G.BCEGUILDLIST_PB_BCEGUILDLIST = BCEGUILDLIST

