-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BceSendGift_pb', package.seeall)


local BCESENDGIFT = protobuf.Descriptor();
local BCESENDGIFT_GIFT_FIELD = protobuf.FieldDescriptor();
local BCESENDGIFT_FROMUSERNAME_FIELD = protobuf.FieldDescriptor();
local BCESENDGIFT_TOUSERIDSTR_FIELD = protobuf.FieldDescriptor();

BCESENDGIFT_GIFT_FIELD.name = "gift"
BCESENDGIFT_GIFT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceSendGift.gift"
BCESENDGIFT_GIFT_FIELD.number = 1
BCESENDGIFT_GIFT_FIELD.index = 0
BCESENDGIFT_GIFT_FIELD.label = 3
BCESENDGIFT_GIFT_FIELD.has_default_value = false
BCESENDGIFT_GIFT_FIELD.default_value = {}
BCESENDGIFT_GIFT_FIELD.message_type = GIFT_PB_GIFT
BCESENDGIFT_GIFT_FIELD.type = 11
BCESENDGIFT_GIFT_FIELD.cpp_type = 10

BCESENDGIFT_FROMUSERNAME_FIELD.name = "fromUserName"
BCESENDGIFT_FROMUSERNAME_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceSendGift.fromUserName"
BCESENDGIFT_FROMUSERNAME_FIELD.number = 2
BCESENDGIFT_FROMUSERNAME_FIELD.index = 1
BCESENDGIFT_FROMUSERNAME_FIELD.label = 2
BCESENDGIFT_FROMUSERNAME_FIELD.has_default_value = false
BCESENDGIFT_FROMUSERNAME_FIELD.default_value = ""
BCESENDGIFT_FROMUSERNAME_FIELD.type = 9
BCESENDGIFT_FROMUSERNAME_FIELD.cpp_type = 9

BCESENDGIFT_TOUSERIDSTR_FIELD.name = "toUserIdStr"
BCESENDGIFT_TOUSERIDSTR_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BceSendGift.toUserIdStr"
BCESENDGIFT_TOUSERIDSTR_FIELD.number = 3
BCESENDGIFT_TOUSERIDSTR_FIELD.index = 2
BCESENDGIFT_TOUSERIDSTR_FIELD.label = 2
BCESENDGIFT_TOUSERIDSTR_FIELD.has_default_value = false
BCESENDGIFT_TOUSERIDSTR_FIELD.default_value = ""
BCESENDGIFT_TOUSERIDSTR_FIELD.type = 9
BCESENDGIFT_TOUSERIDSTR_FIELD.cpp_type = 9

BCESENDGIFT.name = "BceSendGift"
BCESENDGIFT.full_name = ".com.xinqihd.sns.gameserver.proto.BceSendGift"
BCESENDGIFT.nested_types = {}
BCESENDGIFT.enum_types = {}
BCESENDGIFT.fields = {BCESENDGIFT_GIFT_FIELD, BCESENDGIFT_FROMUSERNAME_FIELD, BCESENDGIFT_TOUSERIDSTR_FIELD}
BCESENDGIFT.is_extendable = false
BCESENDGIFT.extensions = {}

BceSendGift = protobuf.Message(BCESENDGIFT)
_G.BCESENDGIFT_PB_BCESENDGIFT = BCESENDGIFT

