-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BseAnswerInvite_pb', package.seeall)


local BSEANSWERINVITE = protobuf.Descriptor();
local BSEANSWERINVITE_UID_FIELD = protobuf.FieldDescriptor();
local BSEANSWERINVITE_RESULT_FIELD = protobuf.FieldDescriptor();

BSEANSWERINVITE_UID_FIELD.name = "uid"
BSEANSWERINVITE_UID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BseAnswerInvite.uid"
BSEANSWERINVITE_UID_FIELD.number = 1
BSEANSWERINVITE_UID_FIELD.index = 0
BSEANSWERINVITE_UID_FIELD.label = 2
BSEANSWERINVITE_UID_FIELD.has_default_value = false
BSEANSWERINVITE_UID_FIELD.default_value = ""
BSEANSWERINVITE_UID_FIELD.type = 9
BSEANSWERINVITE_UID_FIELD.cpp_type = 9

BSEANSWERINVITE_RESULT_FIELD.name = "result"
BSEANSWERINVITE_RESULT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.BseAnswerInvite.result"
BSEANSWERINVITE_RESULT_FIELD.number = 2
BSEANSWERINVITE_RESULT_FIELD.index = 1
BSEANSWERINVITE_RESULT_FIELD.label = 2
BSEANSWERINVITE_RESULT_FIELD.has_default_value = false
BSEANSWERINVITE_RESULT_FIELD.default_value = 0
BSEANSWERINVITE_RESULT_FIELD.type = 5
BSEANSWERINVITE_RESULT_FIELD.cpp_type = 1

BSEANSWERINVITE.name = "BseAnswerInvite"
BSEANSWERINVITE.full_name = ".com.xinqihd.sns.gameserver.proto.BseAnswerInvite"
BSEANSWERINVITE.nested_types = {}
BSEANSWERINVITE.enum_types = {}
BSEANSWERINVITE.fields = {BSEANSWERINVITE_UID_FIELD, BSEANSWERINVITE_RESULT_FIELD}
BSEANSWERINVITE.is_extendable = false
BSEANSWERINVITE.extensions = {}

BseAnswerInvite = protobuf.Message(BSEANSWERINVITE)
_G.BSEANSWERINVITE_PB_BSEANSWERINVITE = BSEANSWERINVITE

