-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('LeaveMessage_pb', package.seeall)


local LEAVEMESSAGE = protobuf.Descriptor();
local LEAVEMESSAGE_UID_FIELD = protobuf.FieldDescriptor();
local LEAVEMESSAGE_NAME_FIELD = protobuf.FieldDescriptor();
local LEAVEMESSAGE_CONTEXT_FIELD = protobuf.FieldDescriptor();
local LEAVEMESSAGE_TIME_FIELD = protobuf.FieldDescriptor();
local LEAVEMESSAGE_UNREAD_FIELD = protobuf.FieldDescriptor();
local LEAVEMESSAGE_PROTS_FIELD = protobuf.FieldDescriptor();

LEAVEMESSAGE_UID_FIELD.name = "uid"
LEAVEMESSAGE_UID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.uid"
LEAVEMESSAGE_UID_FIELD.number = 1
LEAVEMESSAGE_UID_FIELD.index = 0
LEAVEMESSAGE_UID_FIELD.label = 1
LEAVEMESSAGE_UID_FIELD.has_default_value = false
LEAVEMESSAGE_UID_FIELD.default_value = ""
LEAVEMESSAGE_UID_FIELD.type = 9
LEAVEMESSAGE_UID_FIELD.cpp_type = 9

LEAVEMESSAGE_NAME_FIELD.name = "name"
LEAVEMESSAGE_NAME_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.name"
LEAVEMESSAGE_NAME_FIELD.number = 2
LEAVEMESSAGE_NAME_FIELD.index = 1
LEAVEMESSAGE_NAME_FIELD.label = 1
LEAVEMESSAGE_NAME_FIELD.has_default_value = false
LEAVEMESSAGE_NAME_FIELD.default_value = ""
LEAVEMESSAGE_NAME_FIELD.type = 9
LEAVEMESSAGE_NAME_FIELD.cpp_type = 9

LEAVEMESSAGE_CONTEXT_FIELD.name = "context"
LEAVEMESSAGE_CONTEXT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.context"
LEAVEMESSAGE_CONTEXT_FIELD.number = 3
LEAVEMESSAGE_CONTEXT_FIELD.index = 2
LEAVEMESSAGE_CONTEXT_FIELD.label = 1
LEAVEMESSAGE_CONTEXT_FIELD.has_default_value = false
LEAVEMESSAGE_CONTEXT_FIELD.default_value = ""
LEAVEMESSAGE_CONTEXT_FIELD.type = 9
LEAVEMESSAGE_CONTEXT_FIELD.cpp_type = 9

LEAVEMESSAGE_TIME_FIELD.name = "time"
LEAVEMESSAGE_TIME_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.time"
LEAVEMESSAGE_TIME_FIELD.number = 4
LEAVEMESSAGE_TIME_FIELD.index = 3
LEAVEMESSAGE_TIME_FIELD.label = 1
LEAVEMESSAGE_TIME_FIELD.has_default_value = false
LEAVEMESSAGE_TIME_FIELD.default_value = 0
LEAVEMESSAGE_TIME_FIELD.type = 3
LEAVEMESSAGE_TIME_FIELD.cpp_type = 2

LEAVEMESSAGE_UNREAD_FIELD.name = "unread"
LEAVEMESSAGE_UNREAD_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.unread"
LEAVEMESSAGE_UNREAD_FIELD.number = 5
LEAVEMESSAGE_UNREAD_FIELD.index = 4
LEAVEMESSAGE_UNREAD_FIELD.label = 1
LEAVEMESSAGE_UNREAD_FIELD.has_default_value = true
LEAVEMESSAGE_UNREAD_FIELD.default_value = false
LEAVEMESSAGE_UNREAD_FIELD.type = 8
LEAVEMESSAGE_UNREAD_FIELD.cpp_type = 7

LEAVEMESSAGE_PROTS_FIELD.name = "prots"
LEAVEMESSAGE_PROTS_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage.prots"
LEAVEMESSAGE_PROTS_FIELD.number = 6
LEAVEMESSAGE_PROTS_FIELD.index = 5
LEAVEMESSAGE_PROTS_FIELD.label = 3
LEAVEMESSAGE_PROTS_FIELD.has_default_value = false
LEAVEMESSAGE_PROTS_FIELD.default_value = {}
LEAVEMESSAGE_PROTS_FIELD.message_type = PROPDATA_PB_PROPDATA
LEAVEMESSAGE_PROTS_FIELD.type = 11
LEAVEMESSAGE_PROTS_FIELD.cpp_type = 10

LEAVEMESSAGE.name = "LeaveMessage"
LEAVEMESSAGE.full_name = ".com.xinqihd.sns.gameserver.proto.LeaveMessage"
LEAVEMESSAGE.nested_types = {}
LEAVEMESSAGE.enum_types = {}
LEAVEMESSAGE.fields = {LEAVEMESSAGE_UID_FIELD, LEAVEMESSAGE_NAME_FIELD, LEAVEMESSAGE_CONTEXT_FIELD, LEAVEMESSAGE_TIME_FIELD, LEAVEMESSAGE_UNREAD_FIELD, LEAVEMESSAGE_PROTS_FIELD}
LEAVEMESSAGE.is_extendable = false
LEAVEMESSAGE.extensions = {}

LeaveMessage = protobuf.Message(LEAVEMESSAGE)
_G.LEAVEMESSAGE_PB_LEAVEMESSAGE = LEAVEMESSAGE

