-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('RoleInfo_pb', package.seeall)


local ROLEINFO = protobuf.Descriptor();
local ROLEINFO_SESSIONID_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_USERID_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_CAMPID_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_USERNAME_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GENDER_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_EXP_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_WINODDS_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_WINS_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ROOMIDX_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_STARTPOS_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_MOVESPEED_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_TOOL1_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_TOOL2_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_TOOL3_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ATTACK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_DEFEND_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_AGILITY_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_LUCK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_BLOOD_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_THEW_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_DAMAGE_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_SKIN_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_POWER_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDATTACK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDDEFEND_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDAGILITY_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDLUCK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDBLOOD_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDTHEW_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDDAMAGE_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDSKIN_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ADDPOWER_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_EQUIP_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_HIDEHAT_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_HIDEGLASSES_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_HIDESUIT_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_BATTLECOUNT_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_BATTLEROOMIDX_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_YELLOWDMD_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_YELLOWDMDYEAR_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_YELLOWDMDLV_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_DOUBLEEXP_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_STARTPOSX_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_STARTPOSY_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_LESSLV5_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_ROLETYPEID_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDID_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDNAME_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDATTACK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDDEFEND_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDAGILITY_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDLUCK_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDBLOOD_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDTHEW_FIELD = protobuf.FieldDescriptor();
local ROLEINFO_GUILDPOWER_FIELD = protobuf.FieldDescriptor();

ROLEINFO_SESSIONID_FIELD.name = "sessionId"
ROLEINFO_SESSIONID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.sessionId"
ROLEINFO_SESSIONID_FIELD.number = 1
ROLEINFO_SESSIONID_FIELD.index = 0
ROLEINFO_SESSIONID_FIELD.label = 2
ROLEINFO_SESSIONID_FIELD.has_default_value = false
ROLEINFO_SESSIONID_FIELD.default_value = ""
ROLEINFO_SESSIONID_FIELD.type = 9
ROLEINFO_SESSIONID_FIELD.cpp_type = 9

ROLEINFO_USERID_FIELD.name = "userId"
ROLEINFO_USERID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.userId"
ROLEINFO_USERID_FIELD.number = 2
ROLEINFO_USERID_FIELD.index = 1
ROLEINFO_USERID_FIELD.label = 2
ROLEINFO_USERID_FIELD.has_default_value = false
ROLEINFO_USERID_FIELD.default_value = ""
ROLEINFO_USERID_FIELD.type = 9
ROLEINFO_USERID_FIELD.cpp_type = 9

ROLEINFO_CAMPID_FIELD.name = "campId"
ROLEINFO_CAMPID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.campId"
ROLEINFO_CAMPID_FIELD.number = 3
ROLEINFO_CAMPID_FIELD.index = 2
ROLEINFO_CAMPID_FIELD.label = 2
ROLEINFO_CAMPID_FIELD.has_default_value = false
ROLEINFO_CAMPID_FIELD.default_value = 0
ROLEINFO_CAMPID_FIELD.type = 13
ROLEINFO_CAMPID_FIELD.cpp_type = 3

ROLEINFO_USERNAME_FIELD.name = "userName"
ROLEINFO_USERNAME_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.userName"
ROLEINFO_USERNAME_FIELD.number = 4
ROLEINFO_USERNAME_FIELD.index = 3
ROLEINFO_USERNAME_FIELD.label = 2
ROLEINFO_USERNAME_FIELD.has_default_value = false
ROLEINFO_USERNAME_FIELD.default_value = ""
ROLEINFO_USERNAME_FIELD.type = 9
ROLEINFO_USERNAME_FIELD.cpp_type = 9

ROLEINFO_GENDER_FIELD.name = "gender"
ROLEINFO_GENDER_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.gender"
ROLEINFO_GENDER_FIELD.number = 5
ROLEINFO_GENDER_FIELD.index = 4
ROLEINFO_GENDER_FIELD.label = 2
ROLEINFO_GENDER_FIELD.has_default_value = false
ROLEINFO_GENDER_FIELD.default_value = 0
ROLEINFO_GENDER_FIELD.type = 13
ROLEINFO_GENDER_FIELD.cpp_type = 3

ROLEINFO_LEVEL_FIELD.name = "level"
ROLEINFO_LEVEL_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.level"
ROLEINFO_LEVEL_FIELD.number = 6
ROLEINFO_LEVEL_FIELD.index = 5
ROLEINFO_LEVEL_FIELD.label = 2
ROLEINFO_LEVEL_FIELD.has_default_value = false
ROLEINFO_LEVEL_FIELD.default_value = 0
ROLEINFO_LEVEL_FIELD.type = 13
ROLEINFO_LEVEL_FIELD.cpp_type = 3

ROLEINFO_EXP_FIELD.name = "exp"
ROLEINFO_EXP_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.exp"
ROLEINFO_EXP_FIELD.number = 7
ROLEINFO_EXP_FIELD.index = 6
ROLEINFO_EXP_FIELD.label = 2
ROLEINFO_EXP_FIELD.has_default_value = false
ROLEINFO_EXP_FIELD.default_value = 0
ROLEINFO_EXP_FIELD.type = 13
ROLEINFO_EXP_FIELD.cpp_type = 3

ROLEINFO_WINODDS_FIELD.name = "winOdds"
ROLEINFO_WINODDS_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.winOdds"
ROLEINFO_WINODDS_FIELD.number = 8
ROLEINFO_WINODDS_FIELD.index = 7
ROLEINFO_WINODDS_FIELD.label = 2
ROLEINFO_WINODDS_FIELD.has_default_value = false
ROLEINFO_WINODDS_FIELD.default_value = 0
ROLEINFO_WINODDS_FIELD.type = 13
ROLEINFO_WINODDS_FIELD.cpp_type = 3

ROLEINFO_WINS_FIELD.name = "wins"
ROLEINFO_WINS_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.wins"
ROLEINFO_WINS_FIELD.number = 9
ROLEINFO_WINS_FIELD.index = 8
ROLEINFO_WINS_FIELD.label = 2
ROLEINFO_WINS_FIELD.has_default_value = false
ROLEINFO_WINS_FIELD.default_value = 0
ROLEINFO_WINS_FIELD.type = 13
ROLEINFO_WINS_FIELD.cpp_type = 3

ROLEINFO_ROOMIDX_FIELD.name = "roomIdx"
ROLEINFO_ROOMIDX_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.roomIdx"
ROLEINFO_ROOMIDX_FIELD.number = 10
ROLEINFO_ROOMIDX_FIELD.index = 9
ROLEINFO_ROOMIDX_FIELD.label = 2
ROLEINFO_ROOMIDX_FIELD.has_default_value = false
ROLEINFO_ROOMIDX_FIELD.default_value = 0
ROLEINFO_ROOMIDX_FIELD.type = 13
ROLEINFO_ROOMIDX_FIELD.cpp_type = 3

ROLEINFO_STARTPOS_FIELD.name = "startPos"
ROLEINFO_STARTPOS_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.startPos"
ROLEINFO_STARTPOS_FIELD.number = 11
ROLEINFO_STARTPOS_FIELD.index = 10
ROLEINFO_STARTPOS_FIELD.label = 1
ROLEINFO_STARTPOS_FIELD.has_default_value = true
ROLEINFO_STARTPOS_FIELD.default_value = 0
ROLEINFO_STARTPOS_FIELD.type = 5
ROLEINFO_STARTPOS_FIELD.cpp_type = 1

ROLEINFO_MOVESPEED_FIELD.name = "moveSpeed"
ROLEINFO_MOVESPEED_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.moveSpeed"
ROLEINFO_MOVESPEED_FIELD.number = 12
ROLEINFO_MOVESPEED_FIELD.index = 11
ROLEINFO_MOVESPEED_FIELD.label = 2
ROLEINFO_MOVESPEED_FIELD.has_default_value = false
ROLEINFO_MOVESPEED_FIELD.default_value = 0
ROLEINFO_MOVESPEED_FIELD.type = 13
ROLEINFO_MOVESPEED_FIELD.cpp_type = 3

ROLEINFO_TOOL1_FIELD.name = "tool1"
ROLEINFO_TOOL1_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.tool1"
ROLEINFO_TOOL1_FIELD.number = 13
ROLEINFO_TOOL1_FIELD.index = 12
ROLEINFO_TOOL1_FIELD.label = 2
ROLEINFO_TOOL1_FIELD.has_default_value = false
ROLEINFO_TOOL1_FIELD.default_value = 0
ROLEINFO_TOOL1_FIELD.type = 13
ROLEINFO_TOOL1_FIELD.cpp_type = 3

ROLEINFO_TOOL2_FIELD.name = "tool2"
ROLEINFO_TOOL2_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.tool2"
ROLEINFO_TOOL2_FIELD.number = 14
ROLEINFO_TOOL2_FIELD.index = 13
ROLEINFO_TOOL2_FIELD.label = 2
ROLEINFO_TOOL2_FIELD.has_default_value = false
ROLEINFO_TOOL2_FIELD.default_value = 0
ROLEINFO_TOOL2_FIELD.type = 13
ROLEINFO_TOOL2_FIELD.cpp_type = 3

ROLEINFO_TOOL3_FIELD.name = "tool3"
ROLEINFO_TOOL3_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.tool3"
ROLEINFO_TOOL3_FIELD.number = 15
ROLEINFO_TOOL3_FIELD.index = 14
ROLEINFO_TOOL3_FIELD.label = 2
ROLEINFO_TOOL3_FIELD.has_default_value = false
ROLEINFO_TOOL3_FIELD.default_value = 0
ROLEINFO_TOOL3_FIELD.type = 13
ROLEINFO_TOOL3_FIELD.cpp_type = 3

ROLEINFO_ATTACK_FIELD.name = "attack"
ROLEINFO_ATTACK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.attack"
ROLEINFO_ATTACK_FIELD.number = 16
ROLEINFO_ATTACK_FIELD.index = 15
ROLEINFO_ATTACK_FIELD.label = 2
ROLEINFO_ATTACK_FIELD.has_default_value = false
ROLEINFO_ATTACK_FIELD.default_value = 0
ROLEINFO_ATTACK_FIELD.type = 13
ROLEINFO_ATTACK_FIELD.cpp_type = 3

ROLEINFO_DEFEND_FIELD.name = "defend"
ROLEINFO_DEFEND_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.defend"
ROLEINFO_DEFEND_FIELD.number = 17
ROLEINFO_DEFEND_FIELD.index = 16
ROLEINFO_DEFEND_FIELD.label = 2
ROLEINFO_DEFEND_FIELD.has_default_value = false
ROLEINFO_DEFEND_FIELD.default_value = 0
ROLEINFO_DEFEND_FIELD.type = 13
ROLEINFO_DEFEND_FIELD.cpp_type = 3

ROLEINFO_AGILITY_FIELD.name = "agility"
ROLEINFO_AGILITY_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.agility"
ROLEINFO_AGILITY_FIELD.number = 18
ROLEINFO_AGILITY_FIELD.index = 17
ROLEINFO_AGILITY_FIELD.label = 2
ROLEINFO_AGILITY_FIELD.has_default_value = false
ROLEINFO_AGILITY_FIELD.default_value = 0
ROLEINFO_AGILITY_FIELD.type = 13
ROLEINFO_AGILITY_FIELD.cpp_type = 3

ROLEINFO_LUCK_FIELD.name = "luck"
ROLEINFO_LUCK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.luck"
ROLEINFO_LUCK_FIELD.number = 19
ROLEINFO_LUCK_FIELD.index = 18
ROLEINFO_LUCK_FIELD.label = 2
ROLEINFO_LUCK_FIELD.has_default_value = false
ROLEINFO_LUCK_FIELD.default_value = 0
ROLEINFO_LUCK_FIELD.type = 13
ROLEINFO_LUCK_FIELD.cpp_type = 3

ROLEINFO_BLOOD_FIELD.name = "blood"
ROLEINFO_BLOOD_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.blood"
ROLEINFO_BLOOD_FIELD.number = 20
ROLEINFO_BLOOD_FIELD.index = 19
ROLEINFO_BLOOD_FIELD.label = 2
ROLEINFO_BLOOD_FIELD.has_default_value = false
ROLEINFO_BLOOD_FIELD.default_value = 0
ROLEINFO_BLOOD_FIELD.type = 13
ROLEINFO_BLOOD_FIELD.cpp_type = 3

ROLEINFO_THEW_FIELD.name = "thew"
ROLEINFO_THEW_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.thew"
ROLEINFO_THEW_FIELD.number = 21
ROLEINFO_THEW_FIELD.index = 20
ROLEINFO_THEW_FIELD.label = 2
ROLEINFO_THEW_FIELD.has_default_value = false
ROLEINFO_THEW_FIELD.default_value = 0
ROLEINFO_THEW_FIELD.type = 13
ROLEINFO_THEW_FIELD.cpp_type = 3

ROLEINFO_DAMAGE_FIELD.name = "damage"
ROLEINFO_DAMAGE_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.damage"
ROLEINFO_DAMAGE_FIELD.number = 22
ROLEINFO_DAMAGE_FIELD.index = 21
ROLEINFO_DAMAGE_FIELD.label = 2
ROLEINFO_DAMAGE_FIELD.has_default_value = false
ROLEINFO_DAMAGE_FIELD.default_value = 0
ROLEINFO_DAMAGE_FIELD.type = 13
ROLEINFO_DAMAGE_FIELD.cpp_type = 3

ROLEINFO_SKIN_FIELD.name = "skin"
ROLEINFO_SKIN_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.skin"
ROLEINFO_SKIN_FIELD.number = 23
ROLEINFO_SKIN_FIELD.index = 22
ROLEINFO_SKIN_FIELD.label = 2
ROLEINFO_SKIN_FIELD.has_default_value = false
ROLEINFO_SKIN_FIELD.default_value = 0
ROLEINFO_SKIN_FIELD.type = 13
ROLEINFO_SKIN_FIELD.cpp_type = 3

ROLEINFO_POWER_FIELD.name = "power"
ROLEINFO_POWER_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.power"
ROLEINFO_POWER_FIELD.number = 24
ROLEINFO_POWER_FIELD.index = 23
ROLEINFO_POWER_FIELD.label = 2
ROLEINFO_POWER_FIELD.has_default_value = false
ROLEINFO_POWER_FIELD.default_value = 0
ROLEINFO_POWER_FIELD.type = 13
ROLEINFO_POWER_FIELD.cpp_type = 3

ROLEINFO_ADDATTACK_FIELD.name = "addAttack"
ROLEINFO_ADDATTACK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addAttack"
ROLEINFO_ADDATTACK_FIELD.number = 25
ROLEINFO_ADDATTACK_FIELD.index = 24
ROLEINFO_ADDATTACK_FIELD.label = 1
ROLEINFO_ADDATTACK_FIELD.has_default_value = false
ROLEINFO_ADDATTACK_FIELD.default_value = 0
ROLEINFO_ADDATTACK_FIELD.type = 13
ROLEINFO_ADDATTACK_FIELD.cpp_type = 3

ROLEINFO_ADDDEFEND_FIELD.name = "addDefend"
ROLEINFO_ADDDEFEND_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addDefend"
ROLEINFO_ADDDEFEND_FIELD.number = 26
ROLEINFO_ADDDEFEND_FIELD.index = 25
ROLEINFO_ADDDEFEND_FIELD.label = 1
ROLEINFO_ADDDEFEND_FIELD.has_default_value = false
ROLEINFO_ADDDEFEND_FIELD.default_value = 0
ROLEINFO_ADDDEFEND_FIELD.type = 13
ROLEINFO_ADDDEFEND_FIELD.cpp_type = 3

ROLEINFO_ADDAGILITY_FIELD.name = "addAgility"
ROLEINFO_ADDAGILITY_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addAgility"
ROLEINFO_ADDAGILITY_FIELD.number = 27
ROLEINFO_ADDAGILITY_FIELD.index = 26
ROLEINFO_ADDAGILITY_FIELD.label = 1
ROLEINFO_ADDAGILITY_FIELD.has_default_value = false
ROLEINFO_ADDAGILITY_FIELD.default_value = 0
ROLEINFO_ADDAGILITY_FIELD.type = 13
ROLEINFO_ADDAGILITY_FIELD.cpp_type = 3

ROLEINFO_ADDLUCK_FIELD.name = "addLuck"
ROLEINFO_ADDLUCK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addLuck"
ROLEINFO_ADDLUCK_FIELD.number = 28
ROLEINFO_ADDLUCK_FIELD.index = 27
ROLEINFO_ADDLUCK_FIELD.label = 1
ROLEINFO_ADDLUCK_FIELD.has_default_value = false
ROLEINFO_ADDLUCK_FIELD.default_value = 0
ROLEINFO_ADDLUCK_FIELD.type = 13
ROLEINFO_ADDLUCK_FIELD.cpp_type = 3

ROLEINFO_ADDBLOOD_FIELD.name = "addBlood"
ROLEINFO_ADDBLOOD_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addBlood"
ROLEINFO_ADDBLOOD_FIELD.number = 29
ROLEINFO_ADDBLOOD_FIELD.index = 28
ROLEINFO_ADDBLOOD_FIELD.label = 1
ROLEINFO_ADDBLOOD_FIELD.has_default_value = false
ROLEINFO_ADDBLOOD_FIELD.default_value = 0
ROLEINFO_ADDBLOOD_FIELD.type = 13
ROLEINFO_ADDBLOOD_FIELD.cpp_type = 3

ROLEINFO_ADDTHEW_FIELD.name = "addThew"
ROLEINFO_ADDTHEW_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addThew"
ROLEINFO_ADDTHEW_FIELD.number = 30
ROLEINFO_ADDTHEW_FIELD.index = 29
ROLEINFO_ADDTHEW_FIELD.label = 1
ROLEINFO_ADDTHEW_FIELD.has_default_value = false
ROLEINFO_ADDTHEW_FIELD.default_value = 0
ROLEINFO_ADDTHEW_FIELD.type = 13
ROLEINFO_ADDTHEW_FIELD.cpp_type = 3

ROLEINFO_ADDDAMAGE_FIELD.name = "addDamage"
ROLEINFO_ADDDAMAGE_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addDamage"
ROLEINFO_ADDDAMAGE_FIELD.number = 31
ROLEINFO_ADDDAMAGE_FIELD.index = 30
ROLEINFO_ADDDAMAGE_FIELD.label = 1
ROLEINFO_ADDDAMAGE_FIELD.has_default_value = false
ROLEINFO_ADDDAMAGE_FIELD.default_value = 0
ROLEINFO_ADDDAMAGE_FIELD.type = 13
ROLEINFO_ADDDAMAGE_FIELD.cpp_type = 3

ROLEINFO_ADDSKIN_FIELD.name = "addSkin"
ROLEINFO_ADDSKIN_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addSkin"
ROLEINFO_ADDSKIN_FIELD.number = 32
ROLEINFO_ADDSKIN_FIELD.index = 31
ROLEINFO_ADDSKIN_FIELD.label = 1
ROLEINFO_ADDSKIN_FIELD.has_default_value = false
ROLEINFO_ADDSKIN_FIELD.default_value = 0
ROLEINFO_ADDSKIN_FIELD.type = 13
ROLEINFO_ADDSKIN_FIELD.cpp_type = 3

ROLEINFO_ADDPOWER_FIELD.name = "addPower"
ROLEINFO_ADDPOWER_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.addPower"
ROLEINFO_ADDPOWER_FIELD.number = 33
ROLEINFO_ADDPOWER_FIELD.index = 32
ROLEINFO_ADDPOWER_FIELD.label = 1
ROLEINFO_ADDPOWER_FIELD.has_default_value = false
ROLEINFO_ADDPOWER_FIELD.default_value = 0
ROLEINFO_ADDPOWER_FIELD.type = 13
ROLEINFO_ADDPOWER_FIELD.cpp_type = 3

ROLEINFO_EQUIP_FIELD.name = "equip"
ROLEINFO_EQUIP_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.equip"
ROLEINFO_EQUIP_FIELD.number = 35
ROLEINFO_EQUIP_FIELD.index = 33
ROLEINFO_EQUIP_FIELD.label = 3
ROLEINFO_EQUIP_FIELD.has_default_value = false
ROLEINFO_EQUIP_FIELD.default_value = {}
ROLEINFO_EQUIP_FIELD.message_type = PROPDATA_PB_PROPDATA
ROLEINFO_EQUIP_FIELD.type = 11
ROLEINFO_EQUIP_FIELD.cpp_type = 10

ROLEINFO_HIDEHAT_FIELD.name = "hideHat"
ROLEINFO_HIDEHAT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.hideHat"
ROLEINFO_HIDEHAT_FIELD.number = 36
ROLEINFO_HIDEHAT_FIELD.index = 34
ROLEINFO_HIDEHAT_FIELD.label = 2
ROLEINFO_HIDEHAT_FIELD.has_default_value = false
ROLEINFO_HIDEHAT_FIELD.default_value = false
ROLEINFO_HIDEHAT_FIELD.type = 8
ROLEINFO_HIDEHAT_FIELD.cpp_type = 7

ROLEINFO_HIDEGLASSES_FIELD.name = "hideGlasses"
ROLEINFO_HIDEGLASSES_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.hideGlasses"
ROLEINFO_HIDEGLASSES_FIELD.number = 37
ROLEINFO_HIDEGLASSES_FIELD.index = 35
ROLEINFO_HIDEGLASSES_FIELD.label = 2
ROLEINFO_HIDEGLASSES_FIELD.has_default_value = false
ROLEINFO_HIDEGLASSES_FIELD.default_value = false
ROLEINFO_HIDEGLASSES_FIELD.type = 8
ROLEINFO_HIDEGLASSES_FIELD.cpp_type = 7

ROLEINFO_HIDESUIT_FIELD.name = "hideSuit"
ROLEINFO_HIDESUIT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.hideSuit"
ROLEINFO_HIDESUIT_FIELD.number = 38
ROLEINFO_HIDESUIT_FIELD.index = 36
ROLEINFO_HIDESUIT_FIELD.label = 2
ROLEINFO_HIDESUIT_FIELD.has_default_value = false
ROLEINFO_HIDESUIT_FIELD.default_value = false
ROLEINFO_HIDESUIT_FIELD.type = 8
ROLEINFO_HIDESUIT_FIELD.cpp_type = 7

ROLEINFO_BATTLECOUNT_FIELD.name = "battleCount"
ROLEINFO_BATTLECOUNT_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.battleCount"
ROLEINFO_BATTLECOUNT_FIELD.number = 39
ROLEINFO_BATTLECOUNT_FIELD.index = 37
ROLEINFO_BATTLECOUNT_FIELD.label = 2
ROLEINFO_BATTLECOUNT_FIELD.has_default_value = false
ROLEINFO_BATTLECOUNT_FIELD.default_value = 0
ROLEINFO_BATTLECOUNT_FIELD.type = 5
ROLEINFO_BATTLECOUNT_FIELD.cpp_type = 1

ROLEINFO_BATTLEROOMIDX_FIELD.name = "battleRoomIdx"
ROLEINFO_BATTLEROOMIDX_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.battleRoomIdx"
ROLEINFO_BATTLEROOMIDX_FIELD.number = 40
ROLEINFO_BATTLEROOMIDX_FIELD.index = 38
ROLEINFO_BATTLEROOMIDX_FIELD.label = 2
ROLEINFO_BATTLEROOMIDX_FIELD.has_default_value = false
ROLEINFO_BATTLEROOMIDX_FIELD.default_value = 0
ROLEINFO_BATTLEROOMIDX_FIELD.type = 13
ROLEINFO_BATTLEROOMIDX_FIELD.cpp_type = 3

ROLEINFO_YELLOWDMD_FIELD.name = "yellowDmd"
ROLEINFO_YELLOWDMD_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.yellowDmd"
ROLEINFO_YELLOWDMD_FIELD.number = 41
ROLEINFO_YELLOWDMD_FIELD.index = 39
ROLEINFO_YELLOWDMD_FIELD.label = 1
ROLEINFO_YELLOWDMD_FIELD.has_default_value = true
ROLEINFO_YELLOWDMD_FIELD.default_value = false
ROLEINFO_YELLOWDMD_FIELD.type = 8
ROLEINFO_YELLOWDMD_FIELD.cpp_type = 7

ROLEINFO_YELLOWDMDYEAR_FIELD.name = "yellowDmdYear"
ROLEINFO_YELLOWDMDYEAR_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.yellowDmdYear"
ROLEINFO_YELLOWDMDYEAR_FIELD.number = 42
ROLEINFO_YELLOWDMDYEAR_FIELD.index = 40
ROLEINFO_YELLOWDMDYEAR_FIELD.label = 1
ROLEINFO_YELLOWDMDYEAR_FIELD.has_default_value = true
ROLEINFO_YELLOWDMDYEAR_FIELD.default_value = false
ROLEINFO_YELLOWDMDYEAR_FIELD.type = 8
ROLEINFO_YELLOWDMDYEAR_FIELD.cpp_type = 7

ROLEINFO_YELLOWDMDLV_FIELD.name = "yellowDmdLv"
ROLEINFO_YELLOWDMDLV_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.yellowDmdLv"
ROLEINFO_YELLOWDMDLV_FIELD.number = 43
ROLEINFO_YELLOWDMDLV_FIELD.index = 41
ROLEINFO_YELLOWDMDLV_FIELD.label = 1
ROLEINFO_YELLOWDMDLV_FIELD.has_default_value = true
ROLEINFO_YELLOWDMDLV_FIELD.default_value = 0
ROLEINFO_YELLOWDMDLV_FIELD.type = 5
ROLEINFO_YELLOWDMDLV_FIELD.cpp_type = 1

ROLEINFO_DOUBLEEXP_FIELD.name = "doubleexp"
ROLEINFO_DOUBLEEXP_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.doubleexp"
ROLEINFO_DOUBLEEXP_FIELD.number = 44
ROLEINFO_DOUBLEEXP_FIELD.index = 42
ROLEINFO_DOUBLEEXP_FIELD.label = 1
ROLEINFO_DOUBLEEXP_FIELD.has_default_value = true
ROLEINFO_DOUBLEEXP_FIELD.default_value = false
ROLEINFO_DOUBLEEXP_FIELD.type = 8
ROLEINFO_DOUBLEEXP_FIELD.cpp_type = 7

ROLEINFO_STARTPOSX_FIELD.name = "startPosX"
ROLEINFO_STARTPOSX_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.startPosX"
ROLEINFO_STARTPOSX_FIELD.number = 45
ROLEINFO_STARTPOSX_FIELD.index = 43
ROLEINFO_STARTPOSX_FIELD.label = 1
ROLEINFO_STARTPOSX_FIELD.has_default_value = true
ROLEINFO_STARTPOSX_FIELD.default_value = 0
ROLEINFO_STARTPOSX_FIELD.type = 5
ROLEINFO_STARTPOSX_FIELD.cpp_type = 1

ROLEINFO_STARTPOSY_FIELD.name = "startPosY"
ROLEINFO_STARTPOSY_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.startPosY"
ROLEINFO_STARTPOSY_FIELD.number = 46
ROLEINFO_STARTPOSY_FIELD.index = 44
ROLEINFO_STARTPOSY_FIELD.label = 1
ROLEINFO_STARTPOSY_FIELD.has_default_value = true
ROLEINFO_STARTPOSY_FIELD.default_value = 0
ROLEINFO_STARTPOSY_FIELD.type = 5
ROLEINFO_STARTPOSY_FIELD.cpp_type = 1

ROLEINFO_LESSLV5_FIELD.name = "lessLv5"
ROLEINFO_LESSLV5_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.lessLv5"
ROLEINFO_LESSLV5_FIELD.number = 47
ROLEINFO_LESSLV5_FIELD.index = 45
ROLEINFO_LESSLV5_FIELD.label = 1
ROLEINFO_LESSLV5_FIELD.has_default_value = true
ROLEINFO_LESSLV5_FIELD.default_value = false
ROLEINFO_LESSLV5_FIELD.type = 8
ROLEINFO_LESSLV5_FIELD.cpp_type = 7

ROLEINFO_ROLETYPEID_FIELD.name = "roleTypeID"
ROLEINFO_ROLETYPEID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.roleTypeID"
ROLEINFO_ROLETYPEID_FIELD.number = 48
ROLEINFO_ROLETYPEID_FIELD.index = 46
ROLEINFO_ROLETYPEID_FIELD.label = 1
ROLEINFO_ROLETYPEID_FIELD.has_default_value = true
ROLEINFO_ROLETYPEID_FIELD.default_value = 0
ROLEINFO_ROLETYPEID_FIELD.type = 5
ROLEINFO_ROLETYPEID_FIELD.cpp_type = 1

ROLEINFO_GUILDID_FIELD.name = "guildID"
ROLEINFO_GUILDID_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildID"
ROLEINFO_GUILDID_FIELD.number = 49
ROLEINFO_GUILDID_FIELD.index = 47
ROLEINFO_GUILDID_FIELD.label = 1
ROLEINFO_GUILDID_FIELD.has_default_value = true
ROLEINFO_GUILDID_FIELD.default_value = 0
ROLEINFO_GUILDID_FIELD.type = 5
ROLEINFO_GUILDID_FIELD.cpp_type = 1

ROLEINFO_GUILDNAME_FIELD.name = "guildName"
ROLEINFO_GUILDNAME_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildName"
ROLEINFO_GUILDNAME_FIELD.number = 50
ROLEINFO_GUILDNAME_FIELD.index = 48
ROLEINFO_GUILDNAME_FIELD.label = 1
ROLEINFO_GUILDNAME_FIELD.has_default_value = true
ROLEINFO_GUILDNAME_FIELD.default_value = ""
ROLEINFO_GUILDNAME_FIELD.type = 9
ROLEINFO_GUILDNAME_FIELD.cpp_type = 9

ROLEINFO_GUILDATTACK_FIELD.name = "guildAttack"
ROLEINFO_GUILDATTACK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildAttack"
ROLEINFO_GUILDATTACK_FIELD.number = 60
ROLEINFO_GUILDATTACK_FIELD.index = 49
ROLEINFO_GUILDATTACK_FIELD.label = 1
ROLEINFO_GUILDATTACK_FIELD.has_default_value = false
ROLEINFO_GUILDATTACK_FIELD.default_value = 0
ROLEINFO_GUILDATTACK_FIELD.type = 13
ROLEINFO_GUILDATTACK_FIELD.cpp_type = 3

ROLEINFO_GUILDDEFEND_FIELD.name = "guildDefend"
ROLEINFO_GUILDDEFEND_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildDefend"
ROLEINFO_GUILDDEFEND_FIELD.number = 61
ROLEINFO_GUILDDEFEND_FIELD.index = 50
ROLEINFO_GUILDDEFEND_FIELD.label = 1
ROLEINFO_GUILDDEFEND_FIELD.has_default_value = false
ROLEINFO_GUILDDEFEND_FIELD.default_value = 0
ROLEINFO_GUILDDEFEND_FIELD.type = 13
ROLEINFO_GUILDDEFEND_FIELD.cpp_type = 3

ROLEINFO_GUILDAGILITY_FIELD.name = "guildAgility"
ROLEINFO_GUILDAGILITY_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildAgility"
ROLEINFO_GUILDAGILITY_FIELD.number = 62
ROLEINFO_GUILDAGILITY_FIELD.index = 51
ROLEINFO_GUILDAGILITY_FIELD.label = 1
ROLEINFO_GUILDAGILITY_FIELD.has_default_value = false
ROLEINFO_GUILDAGILITY_FIELD.default_value = 0
ROLEINFO_GUILDAGILITY_FIELD.type = 13
ROLEINFO_GUILDAGILITY_FIELD.cpp_type = 3

ROLEINFO_GUILDLUCK_FIELD.name = "guildLuck"
ROLEINFO_GUILDLUCK_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildLuck"
ROLEINFO_GUILDLUCK_FIELD.number = 63
ROLEINFO_GUILDLUCK_FIELD.index = 52
ROLEINFO_GUILDLUCK_FIELD.label = 1
ROLEINFO_GUILDLUCK_FIELD.has_default_value = false
ROLEINFO_GUILDLUCK_FIELD.default_value = 0
ROLEINFO_GUILDLUCK_FIELD.type = 13
ROLEINFO_GUILDLUCK_FIELD.cpp_type = 3

ROLEINFO_GUILDBLOOD_FIELD.name = "guildBlood"
ROLEINFO_GUILDBLOOD_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildBlood"
ROLEINFO_GUILDBLOOD_FIELD.number = 64
ROLEINFO_GUILDBLOOD_FIELD.index = 53
ROLEINFO_GUILDBLOOD_FIELD.label = 1
ROLEINFO_GUILDBLOOD_FIELD.has_default_value = false
ROLEINFO_GUILDBLOOD_FIELD.default_value = 0
ROLEINFO_GUILDBLOOD_FIELD.type = 13
ROLEINFO_GUILDBLOOD_FIELD.cpp_type = 3

ROLEINFO_GUILDTHEW_FIELD.name = "guildThew"
ROLEINFO_GUILDTHEW_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildThew"
ROLEINFO_GUILDTHEW_FIELD.number = 65
ROLEINFO_GUILDTHEW_FIELD.index = 54
ROLEINFO_GUILDTHEW_FIELD.label = 1
ROLEINFO_GUILDTHEW_FIELD.has_default_value = false
ROLEINFO_GUILDTHEW_FIELD.default_value = 0
ROLEINFO_GUILDTHEW_FIELD.type = 13
ROLEINFO_GUILDTHEW_FIELD.cpp_type = 3

ROLEINFO_GUILDPOWER_FIELD.name = "guildPower"
ROLEINFO_GUILDPOWER_FIELD.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo.guildPower"
ROLEINFO_GUILDPOWER_FIELD.number = 66
ROLEINFO_GUILDPOWER_FIELD.index = 55
ROLEINFO_GUILDPOWER_FIELD.label = 1
ROLEINFO_GUILDPOWER_FIELD.has_default_value = false
ROLEINFO_GUILDPOWER_FIELD.default_value = 0
ROLEINFO_GUILDPOWER_FIELD.type = 13
ROLEINFO_GUILDPOWER_FIELD.cpp_type = 3

ROLEINFO.name = "RoleInfo"
ROLEINFO.full_name = ".com.xinqihd.sns.gameserver.proto.RoleInfo"
ROLEINFO.nested_types = {}
ROLEINFO.enum_types = {}
ROLEINFO.fields = {ROLEINFO_SESSIONID_FIELD, ROLEINFO_USERID_FIELD, ROLEINFO_CAMPID_FIELD, ROLEINFO_USERNAME_FIELD, ROLEINFO_GENDER_FIELD, ROLEINFO_LEVEL_FIELD, ROLEINFO_EXP_FIELD, ROLEINFO_WINODDS_FIELD, ROLEINFO_WINS_FIELD, ROLEINFO_ROOMIDX_FIELD, ROLEINFO_STARTPOS_FIELD, ROLEINFO_MOVESPEED_FIELD, ROLEINFO_TOOL1_FIELD, ROLEINFO_TOOL2_FIELD, ROLEINFO_TOOL3_FIELD, ROLEINFO_ATTACK_FIELD, ROLEINFO_DEFEND_FIELD, ROLEINFO_AGILITY_FIELD, ROLEINFO_LUCK_FIELD, ROLEINFO_BLOOD_FIELD, ROLEINFO_THEW_FIELD, ROLEINFO_DAMAGE_FIELD, ROLEINFO_SKIN_FIELD, ROLEINFO_POWER_FIELD, ROLEINFO_ADDATTACK_FIELD, ROLEINFO_ADDDEFEND_FIELD, ROLEINFO_ADDAGILITY_FIELD, ROLEINFO_ADDLUCK_FIELD, ROLEINFO_ADDBLOOD_FIELD, ROLEINFO_ADDTHEW_FIELD, ROLEINFO_ADDDAMAGE_FIELD, ROLEINFO_ADDSKIN_FIELD, ROLEINFO_ADDPOWER_FIELD, ROLEINFO_EQUIP_FIELD, ROLEINFO_HIDEHAT_FIELD, ROLEINFO_HIDEGLASSES_FIELD, ROLEINFO_HIDESUIT_FIELD, ROLEINFO_BATTLECOUNT_FIELD, ROLEINFO_BATTLEROOMIDX_FIELD, ROLEINFO_YELLOWDMD_FIELD, ROLEINFO_YELLOWDMDYEAR_FIELD, ROLEINFO_YELLOWDMDLV_FIELD, ROLEINFO_DOUBLEEXP_FIELD, ROLEINFO_STARTPOSX_FIELD, ROLEINFO_STARTPOSY_FIELD, ROLEINFO_LESSLV5_FIELD, ROLEINFO_ROLETYPEID_FIELD, ROLEINFO_GUILDID_FIELD, ROLEINFO_GUILDNAME_FIELD, ROLEINFO_GUILDATTACK_FIELD, ROLEINFO_GUILDDEFEND_FIELD, ROLEINFO_GUILDAGILITY_FIELD, ROLEINFO_GUILDLUCK_FIELD, ROLEINFO_GUILDBLOOD_FIELD, ROLEINFO_GUILDTHEW_FIELD, ROLEINFO_GUILDPOWER_FIELD}
ROLEINFO.is_extendable = false
ROLEINFO.extensions = {}

RoleInfo = protobuf.Message(ROLEINFO)
_G.ROLEINFO_PB_ROLEINFO = ROLEINFO

